apiVersion: v1
kind: Service
metadata:
  name: vis-monitor1
spec:
  selector:
    app: worker1
  ports:
    - name: http
      port: 80
      targetPort: 9500
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: worker1
spec:
  selector:
    app: worker1
  ports:
    - name: synerex
      port: 700
      targetPort: 10000
    - name: nodeid
      port: 600
      targetPort: 9000

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker1
  labels:
    app: worker1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker1
  template:
    metadata:
      labels:
        app: worker1
    spec:
      containers:
      - name: nodeid-server
        image: synerex-simulation/nodeid-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        ports:
        - containerPort: 9000
      - name: synerex-server
        image: synerex-simulation/synerex-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        ports:
        - containerPort: 10000
      - name: worker-provider
        image: synerex-simulation/worker-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: MASTER_SYNEREX_SERVER
          value: master:700
        - name: MASTER_NODEID_SERVER
          value: master:600
        - name: PORT
          value: '9980'
        ports:
        - containerPort: 9980
      - name: agent-provider
        image: synerex-simulation/agent-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: AREA
          value: "{\"id\":0, \"name\":\"Nagoya\", \"duplicate_area\": [{\"latitude\":35.156431, \"longitude\":136.97285},{\"latitude\":35.156431, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.97285}], \"control_area\": [{\"latitude\":35.156431, \"longitude\":136.97285},{\"latitude\":35.156431, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.97285}]}"
      - name: visualization-provider
        image: synerex-simulation/visualization-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: VIS_ADDRESS
          value: ':9500'

---

apiVersion: v1
kind: Service
metadata:
  name: vis-monitor2
spec:
  selector:
    app: worker2
  ports:
    - name: http
      port: 80
      targetPort: 9500
  type: NodePort
  
---

apiVersion: v1
kind: Service
metadata:
  name: worker2
spec:
  selector:
    app: worker2
  ports:
    - name: synerex
      port: 700
      targetPort: 10000
    - name: nodeid
      port: 600
      targetPort: 9000
  
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker2
  labels:
    app: worker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker2
  template:
    metadata:
      labels:
        app: worker2
    spec:
      containers:
      - name: nodeid-server
        image: synerex-simulation/nodeid-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        ports:
        - containerPort: 9000
      - name: synerex-server
        image: synerex-simulation/synerex-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        ports:
        - containerPort: 10000
      - name: worker-provider
        image: synerex-simulation/worker-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: MASTER_SYNEREX_SERVER
          value: master:700
        - name: MASTER_NODEID_SERVER
          value: master:600
        - name: PORT
          value: '9980'
        ports:
        - containerPort: 9980
      - name: agent-provider
        image: synerex-simulation/agent-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: AREA
          value: "{\"id\":0, \"name\":\"Nagoya\", \"duplicate_area\": [{\"latitude\":35.156431, \"longitude\":136.97285},{\"latitude\":35.156431, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.97285}], \"control_area\": [{\"latitude\":35.156431, \"longitude\":136.97285},{\"latitude\":35.156431, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.981308},{\"latitude\":35.153578, \"longitude\":136.97285}]}"
      - name: visualization-provider
        image: synerex-simulation/visualization-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: :9000
        - name: SYNEREX_SERVER
          value: :10000
        - name: VIS_ADDRESS
          value: ':9500'

---
################################################################
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: gateway1
  labels:
    app: gateway1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway1
  template:
    metadata:
      labels:
        app: gateway1
    spec:
      containers:
      - name: gateway-provider
        image: synerex-simulation/gateway-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: WORKER_SYNEREX_SERVER1
          value: worker1:700
        - name: WORKER_NODEID_SERVER1
          value: worker1:600
        - name: WORKER_SYNEREX_SERVER2
          value: worker2:700
        - name: WORKER_NODEID_SERVER2
          value: worker2:600
        ports:
        - containerPort: 9980
################################################################