apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
    - name: http
      port: 80

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: nodeid-server
        image: synerex-simulation/nodeid-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: localhost:9000
        ports:
        - containerPort: 9000
      - name: synerex-server
        image: synerex-simulation/synerex-server:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: localhost:9000
        - name: SYNEREX_SERVER
          value: localhost:10000
        ports:
        - containerPort: 10000
      - name: master-provider
        image: synerex-simulation/master-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: localhost:9000
        - name: SYNEREX_SERVER
          value: localhost:10000
        - name: PORT
          value: '80'
        ports:
        - containerPort: 80
