apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
    - name: http
      port: 80
      targetPort: 9980

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-provider
        image: synerex-simulation/worker-provider:latest 
        imagePullPolicy: Never
        env: 
        - name: NODEID_SERVER
          value: localhost:9000
        - name: SYNEREX_SERVER
          value: localhost:10000
        - name: MASTER_SYNEREX_SERVER
          value: master:700
        - name: MASTER_NODEID_SERVER
          value: master:600
        - name: PORT
          value: '9980'
        ports:
        - containerPort: 9980
