apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: slow
  hostPath:
    path: /Users/ruihirano/MyProjects/LabProjects/synerex_simulation/kube/data
    type: DirectoryOrCreate

---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pv-slow-claim
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 1Gi
    storageClassName: slow
