// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/agent/agent.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	common "github.com/synerex/synerex_alpha/api/simulation/common"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentType int32

const (
	AgentType_PEDESTRIAN AgentType = 0
	AgentType_CAR        AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "PEDESTRIAN",
	1: "CAR",
}

var AgentType_value = map[string]int32{
	"PEDESTRIAN": 0,
	"CAR":        1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0}
}

type GetAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentsRequest) Reset()         { *m = GetAgentsRequest{} }
func (m *GetAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentsRequest) ProtoMessage()    {}
func (*GetAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{0}
}

func (m *GetAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentsRequest.Unmarshal(m, b)
}
func (m *GetAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentsRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentsRequest.Merge(m, src)
}
func (m *GetAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentsRequest.Size(m)
}
func (m *GetAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentsRequest proto.InternalMessageInfo

type GetAgentsResponse struct {
	AreaId               uint64    `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	AgentType            AgentType `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=api.agent.AgentType" json:"agent_type,omitempty"`
	Agents               []*Agent  `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetAgentsResponse) Reset()         { *m = GetAgentsResponse{} }
func (m *GetAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgentsResponse) ProtoMessage()    {}
func (*GetAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{1}
}

func (m *GetAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentsResponse.Unmarshal(m, b)
}
func (m *GetAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentsResponse.Marshal(b, m, deterministic)
}
func (m *GetAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentsResponse.Merge(m, src)
}
func (m *GetAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgentsResponse.Size(m)
}
func (m *GetAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentsResponse proto.InternalMessageInfo

func (m *GetAgentsResponse) GetAreaId() uint64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *GetAgentsResponse) GetAgentType() AgentType {
	if m != nil {
		return m.AgentType
	}
	return AgentType_PEDESTRIAN
}

func (m *GetAgentsResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type SetAgentsRequest struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentsRequest) Reset()         { *m = SetAgentsRequest{} }
func (m *SetAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*SetAgentsRequest) ProtoMessage()    {}
func (*SetAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{2}
}

func (m *SetAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentsRequest.Unmarshal(m, b)
}
func (m *SetAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentsRequest.Marshal(b, m, deterministic)
}
func (m *SetAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentsRequest.Merge(m, src)
}
func (m *SetAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_SetAgentsRequest.Size(m)
}
func (m *SetAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentsRequest proto.InternalMessageInfo

func (m *SetAgentsRequest) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type SetAgentsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentsResponse) Reset()         { *m = SetAgentsResponse{} }
func (m *SetAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*SetAgentsResponse) ProtoMessage()    {}
func (*SetAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{3}
}

func (m *SetAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentsResponse.Unmarshal(m, b)
}
func (m *SetAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentsResponse.Marshal(b, m, deterministic)
}
func (m *SetAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentsResponse.Merge(m, src)
}
func (m *SetAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_SetAgentsResponse.Size(m)
}
func (m *SetAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentsResponse proto.InternalMessageInfo

type Agent struct {
	Id    uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type  AgentType `protobuf:"varint,2,opt,name=type,proto3,enum=api.agent.AgentType" json:"type,omitempty"`
	Route *Route    `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Agent_Pedestrian
	//	*Agent_Car
	Data                 isAgent_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{4}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_PEDESTRIAN
}

func (m *Agent) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type isAgent_Data interface {
	isAgent_Data()
}

type Agent_Pedestrian struct {
	Pedestrian *Pedestrian `protobuf:"bytes,4,opt,name=pedestrian,proto3,oneof"`
}

type Agent_Car struct {
	Car *Car `protobuf:"bytes,5,opt,name=car,proto3,oneof"`
}

func (*Agent_Pedestrian) isAgent_Data() {}

func (*Agent_Car) isAgent_Data() {}

func (m *Agent) GetData() isAgent_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Agent) GetPedestrian() *Pedestrian {
	if x, ok := m.GetData().(*Agent_Pedestrian); ok {
		return x.Pedestrian
	}
	return nil
}

func (m *Agent) GetCar() *Car {
	if x, ok := m.GetData().(*Agent_Car); ok {
		return x.Car
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Agent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Agent_Pedestrian)(nil),
		(*Agent_Car)(nil),
	}
}

type Route struct {
	Position             *common.Coord   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Direction            float64         `protobuf:"fixed64,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float64         `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Destination          *common.Coord   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Departure            *common.Coord   `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	TransitPoints        []*common.Coord `protobuf:"bytes,6,rep,name=transit_points,json=transitPoints,proto3" json:"transit_points,omitempty"`
	NextTransit          *common.Coord   `protobuf:"bytes,7,opt,name=next_transit,json=nextTransit,proto3" json:"next_transit,omitempty"`
	TotalDistance        float64         `protobuf:"fixed64,8,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	RequiredTime         float64         `protobuf:"fixed64,9,opt,name=required_time,json=requiredTime,proto3" json:"required_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_fce67ac898dc274e, []int{5}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPosition() *common.Coord {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Route) GetDirection() float64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Route) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Route) GetDestination() *common.Coord {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Route) GetDeparture() *common.Coord {
	if m != nil {
		return m.Departure
	}
	return nil
}

func (m *Route) GetTransitPoints() []*common.Coord {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *Route) GetNextTransit() *common.Coord {
	if m != nil {
		return m.NextTransit
	}
	return nil
}

func (m *Route) GetTotalDistance() float64 {
	if m != nil {
		return m.TotalDistance
	}
	return 0
}

func (m *Route) GetRequiredTime() float64 {
	if m != nil {
		return m.RequiredTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.agent.AgentType", AgentType_name, AgentType_value)
	proto.RegisterType((*GetAgentsRequest)(nil), "api.agent.GetAgentsRequest")
	proto.RegisterType((*GetAgentsResponse)(nil), "api.agent.GetAgentsResponse")
	proto.RegisterType((*SetAgentsRequest)(nil), "api.agent.SetAgentsRequest")
	proto.RegisterType((*SetAgentsResponse)(nil), "api.agent.SetAgentsResponse")
	proto.RegisterType((*Agent)(nil), "api.agent.Agent")
	proto.RegisterType((*Route)(nil), "api.agent.Route")
}

func init() { proto.RegisterFile("simulation/agent/agent.proto", fileDescriptor_fce67ac898dc274e) }

var fileDescriptor_fce67ac898dc274e = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0x5d, 0x6f, 0xda, 0x30,
	0x14, 0x86, 0x1b, 0xc2, 0x47, 0x73, 0xf8, 0x10, 0x78, 0x95, 0x16, 0xa1, 0x6a, 0x62, 0xec, 0x43,
	0x68, 0xd2, 0x40, 0x82, 0x4d, 0xdb, 0x45, 0x6f, 0x28, 0xad, 0xd6, 0xde, 0x4c, 0xc8, 0x70, 0xb5,
	0x9b, 0xc8, 0x25, 0x47, 0xad, 0x25, 0x48, 0x5c, 0xdb, 0x91, 0xca, 0x6f, 0xd8, 0xfe, 0xdc, 0xfe,
	0xd1, 0x64, 0x27, 0x84, 0x88, 0x32, 0xf5, 0x86, 0xd8, 0xef, 0x79, 0x5e, 0x7c, 0x5e, 0x1d, 0x1b,
	0xce, 0x15, 0xdf, 0x24, 0x6b, 0xa6, 0x79, 0x1c, 0x8d, 0xd8, 0x3d, 0x46, 0x3a, 0xfd, 0x1d, 0x0a,
	0x19, 0xeb, 0x98, 0x78, 0x4c, 0xf0, 0xa1, 0x15, 0xba, 0x6f, 0x9f, 0x81, 0x02, 0x43, 0x54, 0x5a,
	0x72, 0x16, 0xa5, 0x74, 0xb7, 0xfb, 0x0c, 0x59, 0x31, 0x99, 0xd5, 0xde, 0x14, 0x6a, 0xab, 0x78,
	0xb3, 0xc9, 0x3f, 0x69, 0xbd, 0x4f, 0xa0, 0xfd, 0x03, 0xf5, 0xd4, 0xb8, 0x14, 0xc5, 0xc7, 0x04,
	0x95, 0xee, 0xff, 0x76, 0xa0, 0x53, 0x10, 0x95, 0x88, 0x23, 0x85, 0xe4, 0x35, 0xd4, 0x98, 0x44,
	0x16, 0xf0, 0xd0, 0x77, 0x7a, 0xce, 0xa0, 0x4c, 0xab, 0x66, 0x7b, 0x1b, 0x92, 0x09, 0x80, 0x3d,
	0x35, 0xd0, 0x5b, 0x81, 0x7e, 0xa9, 0xe7, 0x0c, 0x5a, 0xe3, 0xb3, 0x61, 0x9e, 0x60, 0x68, 0xff,
	0x67, 0xb9, 0x15, 0x48, 0x3d, 0xb6, 0x5b, 0x92, 0x01, 0x54, 0xed, 0x46, 0xf9, 0x6e, 0xcf, 0x1d,
	0xd4, 0xc7, 0xed, 0x43, 0x03, 0xcd, 0xea, 0xfd, 0x0b, 0x68, 0x2f, 0x0e, 0x3a, 0x2c, 0xb8, 0x9d,
	0x17, 0xdc, 0xaf, 0xa0, 0xb3, 0x38, 0x8c, 0xd2, 0xff, 0xeb, 0x40, 0xc5, 0x4a, 0xa4, 0x05, 0xa5,
	0x3c, 0x4f, 0x89, 0x87, 0x64, 0x00, 0xe5, 0x17, 0x53, 0x58, 0x82, 0x7c, 0x84, 0x8a, 0x8c, 0x13,
	0x8d, 0xbe, 0xdb, 0x73, 0x0e, 0x3a, 0xa0, 0x46, 0xa7, 0x69, 0x99, 0x5c, 0x00, 0xec, 0x07, 0xe6,
	0x97, 0x2d, 0xdc, 0xb5, 0x70, 0x61, 0x8e, 0xf3, 0x7c, 0x79, 0x73, 0x42, 0x0b, 0x3c, 0xe9, 0x81,
	0xbb, 0x62, 0xd2, 0xaf, 0x58, 0x5b, 0xc3, 0xda, 0xcc, 0x6c, 0x67, 0x4c, 0xde, 0x9c, 0x50, 0x53,
	0xba, 0xac, 0x42, 0x39, 0x64, 0x9a, 0xf5, 0xff, 0xb8, 0x50, 0xb1, 0x07, 0x93, 0xcf, 0x70, 0x2a,
	0x62, 0xc5, 0xcd, 0xc8, 0x6d, 0xb2, 0xfa, 0xb8, 0x93, 0x1a, 0xd3, 0xb9, 0xcf, 0xe2, 0x58, 0x86,
	0x34, 0x47, 0xc8, 0x39, 0x78, 0x21, 0x97, 0xb8, 0xb2, 0xbc, 0xc9, 0xed, 0xd0, 0xbd, 0x40, 0xce,
	0xa0, 0xa2, 0x04, 0x62, 0x68, 0x63, 0x3a, 0x34, 0xdd, 0x90, 0x09, 0xd4, 0x4d, 0x8b, 0x3c, 0xb2,
	0x17, 0x2b, 0x4b, 0x75, 0xe4, 0x94, 0x22, 0x45, 0x46, 0xe0, 0x85, 0x28, 0x98, 0xd4, 0x89, 0xc4,
	0x2c, 0xd1, 0x11, 0xcb, 0x9e, 0x21, 0xdf, 0xa1, 0xa5, 0x25, 0x8b, 0x14, 0xd7, 0x81, 0x88, 0xb9,
	0x99, 0x76, 0xd5, 0x4e, 0xfb, 0x88, 0xab, 0x99, 0x81, 0x73, 0xcb, 0x91, 0x2f, 0xd0, 0x88, 0xf0,
	0x49, 0x07, 0x99, 0xea, 0xd7, 0xfe, 0xdb, 0xa0, 0xc1, 0x96, 0x29, 0x45, 0x3e, 0x40, 0x4b, 0xc7,
	0x9a, 0xad, 0x83, 0x90, 0x2b, 0xcd, 0xa2, 0x15, 0xfa, 0xa7, 0x36, 0x74, 0xd3, 0xaa, 0x57, 0x99,
	0x48, 0xde, 0x41, 0x53, 0xe2, 0x63, 0xc2, 0x25, 0x86, 0x81, 0xe6, 0x1b, 0xf4, 0x3d, 0x4b, 0x35,
	0x76, 0xe2, 0x92, 0x6f, 0xf0, 0xd3, 0x7b, 0xf0, 0xf2, 0x1b, 0x43, 0x5a, 0x00, 0xf3, 0xeb, 0xab,
	0xeb, 0xc5, 0x92, 0xde, 0x4e, 0x7f, 0xb6, 0x4f, 0x48, 0x0d, 0xdc, 0xd9, 0x94, 0xb6, 0x9d, 0xcb,
	0x6f, 0xbf, 0xbe, 0xde, 0x73, 0xfd, 0x90, 0xdc, 0x99, 0xae, 0x46, 0x6a, 0x1b, 0xa1, 0xc4, 0xa7,
	0xdd, 0x37, 0x60, 0x6b, 0xf1, 0xc0, 0x46, 0x4c, 0xf0, 0xd1, 0xe1, 0x03, 0xbf, 0xab, 0xda, 0xd7,
	0x3b, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0x52, 0xf6, 0x10, 0xd1, 0x47, 0x04, 0x00, 0x00,
}
