// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/agent/car.proto

package agent

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Car struct {
	Status               *CarStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Car) Reset()         { *m = Car{} }
func (m *Car) String() string { return proto.CompactTextString(m) }
func (*Car) ProtoMessage()    {}
func (*Car) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df268eb821aa90f, []int{0}
}

func (m *Car) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Car.Unmarshal(m, b)
}
func (m *Car) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Car.Marshal(b, m, deterministic)
}
func (m *Car) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Car.Merge(m, src)
}
func (m *Car) XXX_Size() int {
	return xxx_messageInfo_Car.Size(m)
}
func (m *Car) XXX_DiscardUnknown() {
	xxx_messageInfo_Car.DiscardUnknown(m)
}

var xxx_messageInfo_Car proto.InternalMessageInfo

func (m *Car) GetStatus() *CarStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type CarStatus struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CarStatus) Reset()         { *m = CarStatus{} }
func (m *CarStatus) String() string { return proto.CompactTextString(m) }
func (*CarStatus) ProtoMessage()    {}
func (*CarStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_5df268eb821aa90f, []int{1}
}

func (m *CarStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarStatus.Unmarshal(m, b)
}
func (m *CarStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarStatus.Marshal(b, m, deterministic)
}
func (m *CarStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarStatus.Merge(m, src)
}
func (m *CarStatus) XXX_Size() int {
	return xxx_messageInfo_CarStatus.Size(m)
}
func (m *CarStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CarStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CarStatus proto.InternalMessageInfo

func (m *CarStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Car)(nil), "api.car.Car")
	proto.RegisterType((*CarStatus)(nil), "api.car.CarStatus")
}

func init() { proto.RegisterFile("simulation/agent/car.proto", fileDescriptor_5df268eb821aa90f) }

var fileDescriptor_5df268eb821aa90f = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0xce, 0xcc, 0x2d,
	0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x4f, 0x4e, 0x2c,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x2c, 0xc8, 0xd4, 0x4b, 0x4e, 0x2c, 0x52,
	0x32, 0xe4, 0x62, 0x76, 0x4e, 0x2c, 0x12, 0xd2, 0xe2, 0x62, 0x2b, 0x2e, 0x49, 0x2c, 0x29, 0x2d,
	0x96, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x12, 0xd2, 0x83, 0x2a, 0xd0, 0x73, 0x4e, 0x2c, 0x0a,
	0x06, 0xcb, 0x04, 0x41, 0x55, 0x28, 0xc9, 0x73, 0x71, 0xc2, 0x05, 0x85, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0xc1, 0xda, 0x38, 0x83, 0xc0, 0x6c, 0x27, 0xf3, 0x28, 0xd3, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe2, 0xca, 0xbc, 0xd4, 0xa2, 0xd4, 0x0a, 0x18,
	0x1d, 0x9f, 0x98, 0x53, 0x90, 0x91, 0xa8, 0x9f, 0x58, 0x90, 0xa9, 0x8f, 0xee, 0xbe, 0x24, 0x36,
	0xb0, 0xe3, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x43, 0x5f, 0x45, 0xba, 0x00, 0x00,
	0x00,
}
