apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simulator
  template:
    metadata:
      labels:
        app: simulator
    spec:
      containers:
      - name: simulator
        image: simulation/simulator:latest 
        imagePullPolicy: Never
        tty: true
        env: 
        - name: SIMULATOR_SERVICE_NAME
          value: scenario
        ports:
          - containerPort: 8400
