apiVersion: v1
kind: Service
metadata:
  name: workertest
spec:
  selector:
    app: workertest
  ports:
  - name: synerex
    port: 700
    targetPort: 10000
  - name: nodeid
    port: 600
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: workertest
  labels:
    app: workertest
spec:
  containers:
  - name: nodeid-server
    image: synerex-simulation/nodeid-server:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: synerex-simulation/synerex-server:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: SERVER_NAME
      value: SynerexServertest
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: synerex-simulation/worker-provider:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: MASTER_SYNEREX_SERVER
      value: master:700
    - name: MASTER_NODEID_SERVER
      value: master:600
    - name: PORT
      value: "9980"
    - name: PROVIDER_NAME
      value: WorkerProvidertest
    ports:
    - containerPort: 9980

---
apiVersion: v1
kind: Pod
metadata:
  name: agenttest
  labels:
    app: agenttest
spec:
  containers:
  - name: agent-provider
    image: synerex-simulation/agent-provider:latest
    imagePullPolicy: Never
    env:
    - name: NODEID_SERVER
      value: workertest:600
    - name: SYNEREX_SERVER
      value: workertest:700
    - name: VIS_SYNEREX_SERVER
      value: visualization:700
    - name: VIS_NODEID_SERVER
      value: visualization:600
    - name: AREA
      value: '{"id":0, "name":"Unknown", "duplicate_area": [{"latitude":37.666, "longitude":137.666},{"latitude":37.666,
        "longitude":135.666},{"latitude":35.666, "longitude":135.666},{"latitude":35.666,
        "longitude":137.666}], "control_area": [{"latitude":37.666, "longitude":137.666},{"latitude":37.666,
        "longitude":135.666},{"latitude":35.666, "longitude":135.666},{"latitude":35.666,
        "longitude":137.666}]}'
    - name: PROVIDER_NAME
      value: AgentProvidertest
