// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation/provider/provider.proto

package provider

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	agent "github.com/synerex/synerex_alpha/api/simulation/agent"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProviderType int32

const (
	ProviderType_NODE_ID       ProviderType = 0
	ProviderType_SYNEREX       ProviderType = 1
	ProviderType_MONITOR       ProviderType = 2
	ProviderType_SCENARIO      ProviderType = 3
	ProviderType_AGENT         ProviderType = 4
	ProviderType_VISUALIZATION ProviderType = 5
	ProviderType_CLOCK         ProviderType = 6
)

var ProviderType_name = map[int32]string{
	0: "NODE_ID",
	1: "SYNEREX",
	2: "MONITOR",
	3: "SCENARIO",
	4: "AGENT",
	5: "VISUALIZATION",
	6: "CLOCK",
}

var ProviderType_value = map[string]int32{
	"NODE_ID":       0,
	"SYNEREX":       1,
	"MONITOR":       2,
	"SCENARIO":      3,
	"AGENT":         4,
	"VISUALIZATION": 5,
	"CLOCK":         6,
}

func (x ProviderType) String() string {
	return proto.EnumName(ProviderType_name, int32(x))
}

func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{0}
}

type RegistProviderRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegistProviderRequest) Reset()         { *m = RegistProviderRequest{} }
func (m *RegistProviderRequest) String() string { return proto.CompactTextString(m) }
func (*RegistProviderRequest) ProtoMessage()    {}
func (*RegistProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{0}
}

func (m *RegistProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistProviderRequest.Unmarshal(m, b)
}
func (m *RegistProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistProviderRequest.Marshal(b, m, deterministic)
}
func (m *RegistProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistProviderRequest.Merge(m, src)
}
func (m *RegistProviderRequest) XXX_Size() int {
	return xxx_messageInfo_RegistProviderRequest.Size(m)
}
func (m *RegistProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistProviderRequest proto.InternalMessageInfo

func (m *RegistProviderRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type RegistProviderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistProviderResponse) Reset()         { *m = RegistProviderResponse{} }
func (m *RegistProviderResponse) String() string { return proto.CompactTextString(m) }
func (*RegistProviderResponse) ProtoMessage()    {}
func (*RegistProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{1}
}

func (m *RegistProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistProviderResponse.Unmarshal(m, b)
}
func (m *RegistProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistProviderResponse.Marshal(b, m, deterministic)
}
func (m *RegistProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistProviderResponse.Merge(m, src)
}
func (m *RegistProviderResponse) XXX_Size() int {
	return xxx_messageInfo_RegistProviderResponse.Size(m)
}
func (m *RegistProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistProviderResponse proto.InternalMessageInfo

type KillProviderRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *KillProviderRequest) Reset()         { *m = KillProviderRequest{} }
func (m *KillProviderRequest) String() string { return proto.CompactTextString(m) }
func (*KillProviderRequest) ProtoMessage()    {}
func (*KillProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{2}
}

func (m *KillProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillProviderRequest.Unmarshal(m, b)
}
func (m *KillProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillProviderRequest.Marshal(b, m, deterministic)
}
func (m *KillProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillProviderRequest.Merge(m, src)
}
func (m *KillProviderRequest) XXX_Size() int {
	return xxx_messageInfo_KillProviderRequest.Size(m)
}
func (m *KillProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillProviderRequest proto.InternalMessageInfo

func (m *KillProviderRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type KillProviderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillProviderResponse) Reset()         { *m = KillProviderResponse{} }
func (m *KillProviderResponse) String() string { return proto.CompactTextString(m) }
func (*KillProviderResponse) ProtoMessage()    {}
func (*KillProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{3}
}

func (m *KillProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillProviderResponse.Unmarshal(m, b)
}
func (m *KillProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillProviderResponse.Marshal(b, m, deterministic)
}
func (m *KillProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillProviderResponse.Merge(m, src)
}
func (m *KillProviderResponse) XXX_Size() int {
	return xxx_messageInfo_KillProviderResponse.Size(m)
}
func (m *KillProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillProviderResponse proto.InternalMessageInfo

type DivideProviderRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DivideProviderRequest) Reset()         { *m = DivideProviderRequest{} }
func (m *DivideProviderRequest) String() string { return proto.CompactTextString(m) }
func (*DivideProviderRequest) ProtoMessage()    {}
func (*DivideProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{4}
}

func (m *DivideProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivideProviderRequest.Unmarshal(m, b)
}
func (m *DivideProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivideProviderRequest.Marshal(b, m, deterministic)
}
func (m *DivideProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivideProviderRequest.Merge(m, src)
}
func (m *DivideProviderRequest) XXX_Size() int {
	return xxx_messageInfo_DivideProviderRequest.Size(m)
}
func (m *DivideProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DivideProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DivideProviderRequest proto.InternalMessageInfo

func (m *DivideProviderRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type DivideProviderResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DivideProviderResponse) Reset()         { *m = DivideProviderResponse{} }
func (m *DivideProviderResponse) String() string { return proto.CompactTextString(m) }
func (*DivideProviderResponse) ProtoMessage()    {}
func (*DivideProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{5}
}

func (m *DivideProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DivideProviderResponse.Unmarshal(m, b)
}
func (m *DivideProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DivideProviderResponse.Marshal(b, m, deterministic)
}
func (m *DivideProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DivideProviderResponse.Merge(m, src)
}
func (m *DivideProviderResponse) XXX_Size() int {
	return xxx_messageInfo_DivideProviderResponse.Size(m)
}
func (m *DivideProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DivideProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DivideProviderResponse proto.InternalMessageInfo

type UpdateProvidersRequest struct {
	Providers            []*Provider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateProvidersRequest) Reset()         { *m = UpdateProvidersRequest{} }
func (m *UpdateProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersRequest) ProtoMessage()    {}
func (*UpdateProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{6}
}

func (m *UpdateProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersRequest.Unmarshal(m, b)
}
func (m *UpdateProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersRequest.Merge(m, src)
}
func (m *UpdateProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersRequest.Size(m)
}
func (m *UpdateProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersRequest proto.InternalMessageInfo

func (m *UpdateProvidersRequest) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

type UpdateProvidersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProvidersResponse) Reset()         { *m = UpdateProvidersResponse{} }
func (m *UpdateProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersResponse) ProtoMessage()    {}
func (*UpdateProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{7}
}

func (m *UpdateProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersResponse.Unmarshal(m, b)
}
func (m *UpdateProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersResponse.Merge(m, src)
}
func (m *UpdateProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersResponse.Size(m)
}
func (m *UpdateProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersResponse proto.InternalMessageInfo

type SendProviderStatusRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SendProviderStatusRequest) Reset()         { *m = SendProviderStatusRequest{} }
func (m *SendProviderStatusRequest) String() string { return proto.CompactTextString(m) }
func (*SendProviderStatusRequest) ProtoMessage()    {}
func (*SendProviderStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{8}
}

func (m *SendProviderStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendProviderStatusRequest.Unmarshal(m, b)
}
func (m *SendProviderStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendProviderStatusRequest.Marshal(b, m, deterministic)
}
func (m *SendProviderStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendProviderStatusRequest.Merge(m, src)
}
func (m *SendProviderStatusRequest) XXX_Size() int {
	return xxx_messageInfo_SendProviderStatusRequest.Size(m)
}
func (m *SendProviderStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendProviderStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendProviderStatusRequest proto.InternalMessageInfo

func (m *SendProviderStatusRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type SendProviderStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendProviderStatusResponse) Reset()         { *m = SendProviderStatusResponse{} }
func (m *SendProviderStatusResponse) String() string { return proto.CompactTextString(m) }
func (*SendProviderStatusResponse) ProtoMessage()    {}
func (*SendProviderStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{9}
}

func (m *SendProviderStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendProviderStatusResponse.Unmarshal(m, b)
}
func (m *SendProviderStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendProviderStatusResponse.Marshal(b, m, deterministic)
}
func (m *SendProviderStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendProviderStatusResponse.Merge(m, src)
}
func (m *SendProviderStatusResponse) XXX_Size() int {
	return xxx_messageInfo_SendProviderStatusResponse.Size(m)
}
func (m *SendProviderStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendProviderStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendProviderStatusResponse proto.InternalMessageInfo

type Provider struct {
	Id   uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type ProviderType `protobuf:"varint,3,opt,name=type,proto3,enum=api.provider.ProviderType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//	*Provider_Scenario
	//	*Provider_Agent
	//	*Provider_Visualization
	//	*Provider_Clock
	Data                 isProvider_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{10}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetType() ProviderType {
	if m != nil {
		return m.Type
	}
	return ProviderType_NODE_ID
}

type isProvider_Data interface {
	isProvider_Data()
}

type Provider_Scenario struct {
	Scenario *Scenario `protobuf:"bytes,4,opt,name=scenario,proto3,oneof"`
}

type Provider_Agent struct {
	Agent *Agent `protobuf:"bytes,5,opt,name=agent,proto3,oneof"`
}

type Provider_Visualization struct {
	Visualization *Visualization `protobuf:"bytes,6,opt,name=visualization,proto3,oneof"`
}

type Provider_Clock struct {
	Clock *Clock `protobuf:"bytes,7,opt,name=clock,proto3,oneof"`
}

func (*Provider_Scenario) isProvider_Data() {}

func (*Provider_Agent) isProvider_Data() {}

func (*Provider_Visualization) isProvider_Data() {}

func (*Provider_Clock) isProvider_Data() {}

func (m *Provider) GetData() isProvider_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Provider) GetScenario() *Scenario {
	if x, ok := m.GetData().(*Provider_Scenario); ok {
		return x.Scenario
	}
	return nil
}

func (m *Provider) GetAgent() *Agent {
	if x, ok := m.GetData().(*Provider_Agent); ok {
		return x.Agent
	}
	return nil
}

func (m *Provider) GetVisualization() *Visualization {
	if x, ok := m.GetData().(*Provider_Visualization); ok {
		return x.Visualization
	}
	return nil
}

func (m *Provider) GetClock() *Clock {
	if x, ok := m.GetData().(*Provider_Clock); ok {
		return x.Clock
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Provider) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Provider_Scenario)(nil),
		(*Provider_Agent)(nil),
		(*Provider_Visualization)(nil),
		(*Provider_Clock)(nil),
	}
}

type ProviderStatus struct {
	TotalTime            uint64   `protobuf:"varint,1,opt,name=total_time,json=totalTime,proto3" json:"total_time,omitempty"`
	ComTime              uint64   `protobuf:"varint,2,opt,name=com_time,json=comTime,proto3" json:"com_time,omitempty"`
	LcTime               uint64   `protobuf:"varint,3,opt,name=lc_time,json=lcTime,proto3" json:"lc_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderStatus) Reset()         { *m = ProviderStatus{} }
func (m *ProviderStatus) String() string { return proto.CompactTextString(m) }
func (*ProviderStatus) ProtoMessage()    {}
func (*ProviderStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{11}
}

func (m *ProviderStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderStatus.Unmarshal(m, b)
}
func (m *ProviderStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderStatus.Marshal(b, m, deterministic)
}
func (m *ProviderStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderStatus.Merge(m, src)
}
func (m *ProviderStatus) XXX_Size() int {
	return xxx_messageInfo_ProviderStatus.Size(m)
}
func (m *ProviderStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderStatus proto.InternalMessageInfo

func (m *ProviderStatus) GetTotalTime() uint64 {
	if m != nil {
		return m.TotalTime
	}
	return 0
}

func (m *ProviderStatus) GetComTime() uint64 {
	if m != nil {
		return m.ComTime
	}
	return 0
}

func (m *ProviderStatus) GetLcTime() uint64 {
	if m != nil {
		return m.LcTime
	}
	return 0
}

type Scenario struct {
	Status               *ProviderStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Scenario) Reset()         { *m = Scenario{} }
func (m *Scenario) String() string { return proto.CompactTextString(m) }
func (*Scenario) ProtoMessage()    {}
func (*Scenario) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{12}
}

func (m *Scenario) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scenario.Unmarshal(m, b)
}
func (m *Scenario) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scenario.Marshal(b, m, deterministic)
}
func (m *Scenario) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scenario.Merge(m, src)
}
func (m *Scenario) XXX_Size() int {
	return xxx_messageInfo_Scenario.Size(m)
}
func (m *Scenario) XXX_DiscardUnknown() {
	xxx_messageInfo_Scenario.DiscardUnknown(m)
}

var xxx_messageInfo_Scenario proto.InternalMessageInfo

func (m *Scenario) GetStatus() *ProviderStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Agent struct {
	AreaId               uint64          `protobuf:"varint,1,opt,name=area_id,json=areaId,proto3" json:"area_id,omitempty"`
	AgentType            agent.AgentType `protobuf:"varint,2,opt,name=agent_type,json=agentType,proto3,enum=api.agent.AgentType" json:"agent_type,omitempty"`
	AgentNum             uint64          `protobuf:"varint,3,opt,name=agent_num,json=agentNum,proto3" json:"agent_num,omitempty"`
	Status               *ProviderStatus `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{13}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetAreaId() uint64 {
	if m != nil {
		return m.AreaId
	}
	return 0
}

func (m *Agent) GetAgentType() agent.AgentType {
	if m != nil {
		return m.AgentType
	}
	return agent.AgentType_PEDESTRIAN
}

func (m *Agent) GetAgentNum() uint64 {
	if m != nil {
		return m.AgentNum
	}
	return 0
}

func (m *Agent) GetStatus() *ProviderStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Visualization struct {
	Status               *ProviderStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Visualization) Reset()         { *m = Visualization{} }
func (m *Visualization) String() string { return proto.CompactTextString(m) }
func (*Visualization) ProtoMessage()    {}
func (*Visualization) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{14}
}

func (m *Visualization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visualization.Unmarshal(m, b)
}
func (m *Visualization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visualization.Marshal(b, m, deterministic)
}
func (m *Visualization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visualization.Merge(m, src)
}
func (m *Visualization) XXX_Size() int {
	return xxx_messageInfo_Visualization.Size(m)
}
func (m *Visualization) XXX_DiscardUnknown() {
	xxx_messageInfo_Visualization.DiscardUnknown(m)
}

var xxx_messageInfo_Visualization proto.InternalMessageInfo

func (m *Visualization) GetStatus() *ProviderStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type Clock struct {
	Status               *ProviderStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Clock) Reset()         { *m = Clock{} }
func (m *Clock) String() string { return proto.CompactTextString(m) }
func (*Clock) ProtoMessage()    {}
func (*Clock) Descriptor() ([]byte, []int) {
	return fileDescriptor_d81c3bbd95787d41, []int{15}
}

func (m *Clock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clock.Unmarshal(m, b)
}
func (m *Clock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clock.Marshal(b, m, deterministic)
}
func (m *Clock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clock.Merge(m, src)
}
func (m *Clock) XXX_Size() int {
	return xxx_messageInfo_Clock.Size(m)
}
func (m *Clock) XXX_DiscardUnknown() {
	xxx_messageInfo_Clock.DiscardUnknown(m)
}

var xxx_messageInfo_Clock proto.InternalMessageInfo

func (m *Clock) GetStatus() *ProviderStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.provider.ProviderType", ProviderType_name, ProviderType_value)
	proto.RegisterType((*RegistProviderRequest)(nil), "api.provider.RegistProviderRequest")
	proto.RegisterType((*RegistProviderResponse)(nil), "api.provider.RegistProviderResponse")
	proto.RegisterType((*KillProviderRequest)(nil), "api.provider.KillProviderRequest")
	proto.RegisterType((*KillProviderResponse)(nil), "api.provider.KillProviderResponse")
	proto.RegisterType((*DivideProviderRequest)(nil), "api.provider.DivideProviderRequest")
	proto.RegisterType((*DivideProviderResponse)(nil), "api.provider.DivideProviderResponse")
	proto.RegisterType((*UpdateProvidersRequest)(nil), "api.provider.UpdateProvidersRequest")
	proto.RegisterType((*UpdateProvidersResponse)(nil), "api.provider.UpdateProvidersResponse")
	proto.RegisterType((*SendProviderStatusRequest)(nil), "api.provider.SendProviderStatusRequest")
	proto.RegisterType((*SendProviderStatusResponse)(nil), "api.provider.SendProviderStatusResponse")
	proto.RegisterType((*Provider)(nil), "api.provider.Provider")
	proto.RegisterType((*ProviderStatus)(nil), "api.provider.ProviderStatus")
	proto.RegisterType((*Scenario)(nil), "api.provider.Scenario")
	proto.RegisterType((*Agent)(nil), "api.provider.Agent")
	proto.RegisterType((*Visualization)(nil), "api.provider.Visualization")
	proto.RegisterType((*Clock)(nil), "api.provider.Clock")
}

func init() { proto.RegisterFile("simulation/provider/provider.proto", fileDescriptor_d81c3bbd95787d41) }

var fileDescriptor_d81c3bbd95787d41 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdb, 0x6a, 0xdb, 0x3e,
	0x18, 0x8f, 0x1d, 0xc7, 0x71, 0xbe, 0x1e, 0xf0, 0x5f, 0x6d, 0x53, 0xf7, 0xf0, 0x87, 0xe0, 0xab,
	0xb2, 0x41, 0x02, 0x6d, 0x2f, 0xc6, 0x60, 0xb0, 0x34, 0x0d, 0xab, 0x49, 0x67, 0x0f, 0x27, 0x2d,
	0x5b, 0x6f, 0x82, 0x6a, 0x8b, 0x56, 0xcc, 0xa7, 0x45, 0x72, 0x59, 0xf6, 0x44, 0x7b, 0x87, 0xbd,
	0xdc, 0xb0, 0x6c, 0x67, 0x49, 0x67, 0x06, 0xeb, 0x7a, 0x93, 0x48, 0xfa, 0x9d, 0xa4, 0xef, 0x13,
	0x32, 0x98, 0x8c, 0x86, 0x69, 0x80, 0x39, 0x8d, 0xa3, 0x5e, 0x32, 0x8b, 0x1f, 0xa8, 0x4f, 0x66,
	0x8b, 0x41, 0x37, 0x99, 0xc5, 0x3c, 0x46, 0xeb, 0x38, 0xa1, 0xdd, 0x72, 0x6d, 0xff, 0x70, 0x49,
	0x81, 0xef, 0x48, 0xc4, 0xf3, 0xdf, 0x9c, 0x6b, 0x8e, 0x60, 0xc7, 0x25, 0x77, 0x94, 0xf1, 0x0f,
	0x05, 0xdf, 0x25, 0x5f, 0x52, 0xc2, 0x38, 0x3a, 0x06, 0xad, 0xb4, 0x30, 0xa4, 0x8e, 0x74, 0xb4,
	0x76, 0xdc, 0xee, 0x2e, 0xfb, 0x76, 0x17, 0x82, 0x05, 0xcf, 0x34, 0xa0, 0xfd, 0xd8, 0x8c, 0x25,
	0x71, 0xc4, 0x88, 0x69, 0xc1, 0xd6, 0x88, 0x06, 0xc1, 0x73, 0x84, 0xb4, 0x61, 0x7b, 0xd5, 0xaa,
	0x88, 0x18, 0xc1, 0xce, 0x39, 0xcd, 0x96, 0x9e, 0xe9, 0x24, 0x8f, 0xcd, 0x8a, 0x18, 0x1b, 0xda,
	0x57, 0x89, 0x8f, 0xf9, 0x02, 0x61, 0x65, 0xce, 0x29, 0xb4, 0x4a, 0x3d, 0x33, 0xa4, 0x4e, 0xfd,
	0x0f, 0x41, 0xbf, 0x88, 0xe6, 0x1e, 0xec, 0xfe, 0xe6, 0x57, 0x44, 0x39, 0xb0, 0x37, 0x26, 0x91,
	0x5f, 0x02, 0x63, 0x8e, 0x79, 0xca, 0xfe, 0xe5, 0x54, 0x87, 0xb0, 0x5f, 0x65, 0x58, 0xc4, 0xfd,
	0x90, 0x41, 0x2b, 0x21, 0xb4, 0x09, 0x32, 0xf5, 0x85, 0xb1, 0xe2, 0xca, 0xd4, 0x47, 0x08, 0x94,
	0x08, 0x87, 0xc4, 0x90, 0x3b, 0xd2, 0x51, 0xcb, 0x15, 0x63, 0xd4, 0x05, 0x85, 0xcf, 0x13, 0x62,
	0xd4, 0x3b, 0xd2, 0xd1, 0xe6, 0xf1, 0x7e, 0x75, 0xfc, 0x64, 0x9e, 0x10, 0x57, 0xf0, 0xd0, 0x29,
	0x68, 0xcc, 0x23, 0x11, 0x9e, 0xd1, 0xd8, 0x50, 0xaa, 0xb6, 0x3c, 0x2e, 0xd0, 0x8b, 0x9a, 0xbb,
	0x60, 0xa2, 0x97, 0xd0, 0x10, 0x17, 0xd6, 0x68, 0x08, 0xc9, 0xd6, 0xaa, 0xa4, 0x9f, 0x41, 0x17,
	0x35, 0x37, 0xe7, 0xa0, 0x01, 0x6c, 0x3c, 0x50, 0x96, 0xe2, 0x80, 0x7e, 0x13, 0x37, 0xde, 0x50,
	0x85, 0xe8, 0x60, 0x55, 0x74, 0xbd, 0x4c, 0xb9, 0xa8, 0xb9, 0xab, 0x9a, 0x2c, 0xd1, 0x0b, 0x62,
	0xef, 0xb3, 0xd1, 0xac, 0x4a, 0x1c, 0x64, 0x50, 0x96, 0x28, 0x38, 0x67, 0x2a, 0x28, 0x3e, 0xe6,
	0xd8, 0xf4, 0x60, 0x73, 0xb5, 0xae, 0xe8, 0x7f, 0x00, 0x1e, 0x73, 0x1c, 0x4c, 0x39, 0x0d, 0x49,
	0x51, 0xca, 0x96, 0x58, 0x99, 0xd0, 0x90, 0xa0, 0x3d, 0xd0, 0xbc, 0x38, 0xcc, 0x41, 0x59, 0x80,
	0x4d, 0x2f, 0x0e, 0x05, 0xb4, 0x0b, 0xcd, 0xc0, 0xcb, 0x91, 0xba, 0x40, 0xd4, 0xc0, 0xcb, 0x00,
	0xf3, 0x2d, 0x68, 0x65, 0x8d, 0xd0, 0x29, 0xa8, 0x4c, 0x04, 0x15, 0xed, 0x3f, 0xac, 0xae, 0x7f,
	0xd1, 0xe4, 0x82, 0x6b, 0x7e, 0x97, 0xa0, 0x21, 0x6a, 0x96, 0x85, 0xe0, 0x19, 0xc1, 0xd3, 0x45,
	0x9b, 0xd5, 0x6c, 0x6a, 0xf9, 0xe8, 0x04, 0x40, 0x14, 0x73, 0x2a, 0x9a, 0x2b, 0x8b, 0xe6, 0x6e,
	0x0b, 0xf3, 0xfc, 0xe1, 0x10, 0x72, 0xd1, 0xd6, 0x16, 0x2e, 0x87, 0xe8, 0x00, 0xf2, 0xc9, 0x34,
	0x4a, 0xc3, 0x62, 0xd3, 0x9a, 0x58, 0xb0, 0xd3, 0x70, 0x69, 0xab, 0xca, 0x5f, 0x6c, 0x75, 0x08,
	0x1b, 0x2b, 0x8d, 0x7a, 0xe2, 0x89, 0xdf, 0x40, 0x43, 0xb4, 0xec, 0x69, 0xf2, 0x17, 0x01, 0xac,
	0x2f, 0x5f, 0x65, 0xb4, 0x06, 0x4d, 0xdb, 0x39, 0x1f, 0x4e, 0xad, 0x73, 0xbd, 0x96, 0x4d, 0xc6,
	0x9f, 0xec, 0xa1, 0x3b, 0xfc, 0xa8, 0x4b, 0xd9, 0xe4, 0xbd, 0x63, 0x5b, 0x13, 0xc7, 0xd5, 0x65,
	0xb4, 0x0e, 0xda, 0x78, 0x30, 0xb4, 0xfb, 0xae, 0xe5, 0xe8, 0x75, 0xd4, 0x82, 0x46, 0xff, 0xdd,
	0xd0, 0x9e, 0xe8, 0x0a, 0xfa, 0x0f, 0x36, 0xae, 0xad, 0xf1, 0x55, 0xff, 0xd2, 0xba, 0xe9, 0x4f,
	0x2c, 0xc7, 0xd6, 0x1b, 0x19, 0x3a, 0xb8, 0x74, 0x06, 0x23, 0x5d, 0x3d, 0x7b, 0x7d, 0xf3, 0xea,
	0x8e, 0xf2, 0xfb, 0xf4, 0xb6, 0xeb, 0xc5, 0x61, 0x8f, 0xcd, 0x23, 0x32, 0x23, 0x5f, 0xcb, 0xff,
	0x29, 0x0e, 0x92, 0x7b, 0xdc, 0xc3, 0x09, 0xed, 0x55, 0x7c, 0x05, 0x6e, 0x55, 0xf1, 0xa2, 0x9f,
	0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa4, 0x54, 0x0f, 0x61, 0x23, 0x06, 0x00, 0x00,
}
