apiVersion: v1
kind: Service
metadata:
  name: simulator
spec:
  selector:
    app: simulator
  ports:
  - name: http
    port: 8000
  type: NodePort

---
apiVersion: v1
kind: Pod
metadata:
  name: simulator
  labels:
    app: simulator
spec:
  containers:
  - name: simulator
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/simulator:1.6
    stdin: true
    tty: true
    env:
    - name: MASTER_ADDRESS
      value: http://master:800
    ports:
    - containerPort: 8000
  imagePullSecrets:
  - name: ruirui-regcred

---
apiVersion: v1
kind: Service
metadata:
  name: master
spec:
  selector:
    app: master
  ports:
  - name: synerex
    port: 700
    targetPort: 10000
  - name: nodeid
    port: 600
    targetPort: 9000
  - name: master-provider
    port: 800
    targetPort: 9990

---
apiVersion: v1
kind: Pod
metadata:
  name: master
  labels:
    app: master
spec:
  containers:
  - name: nodeid-server
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/nodeid-server:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/synerex-server:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    ports:
    - containerPort: 10000
  - name: master-provider
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/master-provider:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: PORT
      value: "9990"
    ports:
    - containerPort: 9990
  imagePullSecrets:
  - name: ruirui-regcred

---
apiVersion: v1
kind: Service
metadata:
  name: vis-monitor11
spec:
  selector:
    app: worker11
  ports:
  - name: http
    port: 80
    targetPort: 9500
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: worker11
spec:
  selector:
    app: worker11
  ports:
  - name: synerex
    port: 700
    targetPort: 10000
  - name: nodeid
    port: 600
    targetPort: 9000

---
apiVersion: v1
kind: Pod
metadata:
  name: worker11
  labels:
    app: worker11
spec:
  containers:
  - name: nodeid-server
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/nodeid-server:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    ports:
    - containerPort: 9000
  - name: synerex-server
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/synerex-server:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: SERVER_NAME
      value: SynerexServer11
    ports:
    - containerPort: 10000
  - name: worker-provider
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/worker-provider:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: MASTER_SYNEREX_SERVER
      value: master:700
    - name: MASTER_NODEID_SERVER
      value: master:600
    - name: PORT
      value: "9980"
    - name: PROVIDER_NAME
      value: WorkerProvider11
    ports:
    - containerPort: 9980
  - name: agent-provider
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/agent-provider:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: AREA
      value: '{"id":11, "name":"Unknown", "duplicate_area": [{"latitude":35.3624279,
        "longitude":133.66985069999998},{"latitude":32.951281099999996, "longitude":133.66985069999998},{"latitude":32.951281099999996,
        "longitude":137.29115430000002},{"latitude":35.3624279, "longitude":137.29115430000002}],
        "control_area": [{"latitude":35.161499, "longitude":133.971626},{"latitude":33.15221,
        "longitude":133.971626},{"latitude":33.15221, "longitude":136.989379},{"latitude":35.161499,
        "longitude":136.989379}]}'
    - name: PROVIDER_NAME
      value: AgentProvider11
  - name: visualization-provider
    image: ucl.nuee.nagoya-u.ac.jp/uclab/synerex-simulation/visualization-provider:1.6
    env:
    - name: NODEID_SERVER
      value: :9000
    - name: SYNEREX_SERVER
      value: :10000
    - name: VIS_ADDRESS
      value: :9500
    - name: PROVIDER_NAME
      value: VisProvider11
  imagePullSecrets:
  - name: ruirui-regcred

---
