// Code generated by protoc-gen-go. DO NOT EDIT.
// source: simulation.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusType int32

const (
	StatusType_OK    StatusType = 0
	StatusType_ERROR StatusType = 1
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusType_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{0}
}

type DemandType int32

const (
	DemandType_SET_AGENT_REQUEST        DemandType = 0
	DemandType_GET_AGENT_REQUEST        DemandType = 1
	DemandType_REGIST_PROVIDER_REQUEST  DemandType = 2
	DemandType_UPDATE_PROVIDERS_REQUEST DemandType = 3
	DemandType_SET_CLOCK_REQUEST        DemandType = 4
	DemandType_START_CLOCK_REQUEST      DemandType = 5
	DemandType_STOP_CLOCK_REQUEST       DemandType = 6
	DemandType_FORWARD_CLOCK_REQUEST    DemandType = 7
	DemandType_CREATE_POD_REQUEST       DemandType = 8
	DemandType_DELETE_POD_REQUEST       DemandType = 9
)

var DemandType_name = map[int32]string{
	0: "SET_AGENT_REQUEST",
	1: "GET_AGENT_REQUEST",
	2: "REGIST_PROVIDER_REQUEST",
	3: "UPDATE_PROVIDERS_REQUEST",
	4: "SET_CLOCK_REQUEST",
	5: "START_CLOCK_REQUEST",
	6: "STOP_CLOCK_REQUEST",
	7: "FORWARD_CLOCK_REQUEST",
	8: "CREATE_POD_REQUEST",
	9: "DELETE_POD_REQUEST",
}

var DemandType_value = map[string]int32{
	"SET_AGENT_REQUEST":        0,
	"GET_AGENT_REQUEST":        1,
	"REGIST_PROVIDER_REQUEST":  2,
	"UPDATE_PROVIDERS_REQUEST": 3,
	"SET_CLOCK_REQUEST":        4,
	"START_CLOCK_REQUEST":      5,
	"STOP_CLOCK_REQUEST":       6,
	"FORWARD_CLOCK_REQUEST":    7,
	"CREATE_POD_REQUEST":       8,
	"DELETE_POD_REQUEST":       9,
}

func (x DemandType) String() string {
	return proto.EnumName(DemandType_name, int32(x))
}

func (DemandType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{1}
}

type SupplyType int32

const (
	SupplyType_SET_AGENT_RESPONSE        SupplyType = 0
	SupplyType_GET_AGENT_RESPONSE        SupplyType = 1
	SupplyType_REGIST_PROVIDER_RESPONSE  SupplyType = 2
	SupplyType_UPDATE_PROVIDERS_RESPONSE SupplyType = 3
	SupplyType_SET_CLOCK_RESPONSE        SupplyType = 4
	SupplyType_START_CLOCK_RESPONSE      SupplyType = 5
	SupplyType_STOP_CLOCK_RESPONSE       SupplyType = 6
	SupplyType_FORWARD_CLOCK_RESPONSE    SupplyType = 7
	SupplyType_CREATE_POD_RESPONSE       SupplyType = 8
	SupplyType_DELETE_POD_RESPONSE       SupplyType = 9
)

var SupplyType_name = map[int32]string{
	0: "SET_AGENT_RESPONSE",
	1: "GET_AGENT_RESPONSE",
	2: "REGIST_PROVIDER_RESPONSE",
	3: "UPDATE_PROVIDERS_RESPONSE",
	4: "SET_CLOCK_RESPONSE",
	5: "START_CLOCK_RESPONSE",
	6: "STOP_CLOCK_RESPONSE",
	7: "FORWARD_CLOCK_RESPONSE",
	8: "CREATE_POD_RESPONSE",
	9: "DELETE_POD_RESPONSE",
}

var SupplyType_value = map[string]int32{
	"SET_AGENT_RESPONSE":        0,
	"GET_AGENT_RESPONSE":        1,
	"REGIST_PROVIDER_RESPONSE":  2,
	"UPDATE_PROVIDERS_RESPONSE": 3,
	"SET_CLOCK_RESPONSE":        4,
	"START_CLOCK_RESPONSE":      5,
	"STOP_CLOCK_RESPONSE":       6,
	"FORWARD_CLOCK_RESPONSE":    7,
	"CREATE_POD_RESPONSE":       8,
	"DELETE_POD_RESPONSE":       9,
}

func (x SupplyType) String() string {
	return proto.EnumName(SupplyType_name, int32(x))
}

func (SupplyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{2}
}

type ProviderType int32

const (
	ProviderType_MASTER        ProviderType = 0
	ProviderType_WORKER        ProviderType = 1
	ProviderType_AGENT         ProviderType = 2
	ProviderType_VISUALIZATION ProviderType = 3
	ProviderType_GATEWAY       ProviderType = 4
)

var ProviderType_name = map[int32]string{
	0: "MASTER",
	1: "WORKER",
	2: "AGENT",
	3: "VISUALIZATION",
	4: "GATEWAY",
}

var ProviderType_value = map[string]int32{
	"MASTER":        0,
	"WORKER":        1,
	"AGENT":         2,
	"VISUALIZATION": 3,
	"GATEWAY":       4,
}

func (x ProviderType) String() string {
	return proto.EnumName(ProviderType_name, int32(x))
}

func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{3}
}

type AgentType int32

const (
	AgentType_PEDESTRIAN AgentType = 0
	AgentType_CAR        AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "PEDESTRIAN",
	1: "CAR",
}

var AgentType_value = map[string]int32{
	"PEDESTRIAN": 0,
	"CAR":        1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{4}
}

type SimDemand struct {
	MsgId    uint64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// provider info
	Type    DemandType `protobuf:"varint,3,opt,name=type,proto3,enum=api.DemandType" json:"type,omitempty"`
	Targets []uint64   `protobuf:"varint,4,rep,packed,name=targets,proto3" json:"targets,omitempty"`
	// meta data
	Meta string `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	// demand data
	//
	// Types that are valid to be assigned to Data:
	//	*SimDemand_SetAgentRequest
	//	*SimDemand_RegistProviderRequest
	//	*SimDemand_UpdateProvidersRequest
	//	*SimDemand_SetClockRequest
	//	*SimDemand_StartClockRequest
	//	*SimDemand_StopClockRequest
	//	*SimDemand_ForwardClockRequest
	//	*SimDemand_GetAgentRequest
	//	*SimDemand_CreatePodRequest
	//	*SimDemand_DeletePodRequest
	Data                 isSimDemand_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimDemand) Reset()         { *m = SimDemand{} }
func (m *SimDemand) String() string { return proto.CompactTextString(m) }
func (*SimDemand) ProtoMessage()    {}
func (*SimDemand) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{0}
}

func (m *SimDemand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimDemand.Unmarshal(m, b)
}
func (m *SimDemand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimDemand.Marshal(b, m, deterministic)
}
func (m *SimDemand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimDemand.Merge(m, src)
}
func (m *SimDemand) XXX_Size() int {
	return xxx_messageInfo_SimDemand.Size(m)
}
func (m *SimDemand) XXX_DiscardUnknown() {
	xxx_messageInfo_SimDemand.DiscardUnknown(m)
}

var xxx_messageInfo_SimDemand proto.InternalMessageInfo

func (m *SimDemand) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *SimDemand) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *SimDemand) GetType() DemandType {
	if m != nil {
		return m.Type
	}
	return DemandType_SET_AGENT_REQUEST
}

func (m *SimDemand) GetTargets() []uint64 {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *SimDemand) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type isSimDemand_Data interface {
	isSimDemand_Data()
}

type SimDemand_SetAgentRequest struct {
	SetAgentRequest *SetAgentRequest `protobuf:"bytes,6,opt,name=set_agent_request,json=setAgentRequest,proto3,oneof"`
}

type SimDemand_RegistProviderRequest struct {
	RegistProviderRequest *RegistProviderRequest `protobuf:"bytes,7,opt,name=regist_provider_request,json=registProviderRequest,proto3,oneof"`
}

type SimDemand_UpdateProvidersRequest struct {
	UpdateProvidersRequest *UpdateProvidersRequest `protobuf:"bytes,8,opt,name=update_providers_request,json=updateProvidersRequest,proto3,oneof"`
}

type SimDemand_SetClockRequest struct {
	SetClockRequest *SetClockRequest `protobuf:"bytes,9,opt,name=set_clock_request,json=setClockRequest,proto3,oneof"`
}

type SimDemand_StartClockRequest struct {
	StartClockRequest *StartClockRequest `protobuf:"bytes,10,opt,name=start_clock_request,json=startClockRequest,proto3,oneof"`
}

type SimDemand_StopClockRequest struct {
	StopClockRequest *StopClockRequest `protobuf:"bytes,11,opt,name=stop_clock_request,json=stopClockRequest,proto3,oneof"`
}

type SimDemand_ForwardClockRequest struct {
	ForwardClockRequest *ForwardClockRequest `protobuf:"bytes,12,opt,name=forward_clock_request,json=forwardClockRequest,proto3,oneof"`
}

type SimDemand_GetAgentRequest struct {
	GetAgentRequest *GetAgentRequest `protobuf:"bytes,13,opt,name=get_agent_request,json=getAgentRequest,proto3,oneof"`
}

type SimDemand_CreatePodRequest struct {
	CreatePodRequest *CreatePodRequest `protobuf:"bytes,14,opt,name=create_pod_request,json=createPodRequest,proto3,oneof"`
}

type SimDemand_DeletePodRequest struct {
	DeletePodRequest *DeletePodRequest `protobuf:"bytes,15,opt,name=delete_pod_request,json=deletePodRequest,proto3,oneof"`
}

func (*SimDemand_SetAgentRequest) isSimDemand_Data() {}

func (*SimDemand_RegistProviderRequest) isSimDemand_Data() {}

func (*SimDemand_UpdateProvidersRequest) isSimDemand_Data() {}

func (*SimDemand_SetClockRequest) isSimDemand_Data() {}

func (*SimDemand_StartClockRequest) isSimDemand_Data() {}

func (*SimDemand_StopClockRequest) isSimDemand_Data() {}

func (*SimDemand_ForwardClockRequest) isSimDemand_Data() {}

func (*SimDemand_GetAgentRequest) isSimDemand_Data() {}

func (*SimDemand_CreatePodRequest) isSimDemand_Data() {}

func (*SimDemand_DeletePodRequest) isSimDemand_Data() {}

func (m *SimDemand) GetData() isSimDemand_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SimDemand) GetSetAgentRequest() *SetAgentRequest {
	if x, ok := m.GetData().(*SimDemand_SetAgentRequest); ok {
		return x.SetAgentRequest
	}
	return nil
}

func (m *SimDemand) GetRegistProviderRequest() *RegistProviderRequest {
	if x, ok := m.GetData().(*SimDemand_RegistProviderRequest); ok {
		return x.RegistProviderRequest
	}
	return nil
}

func (m *SimDemand) GetUpdateProvidersRequest() *UpdateProvidersRequest {
	if x, ok := m.GetData().(*SimDemand_UpdateProvidersRequest); ok {
		return x.UpdateProvidersRequest
	}
	return nil
}

func (m *SimDemand) GetSetClockRequest() *SetClockRequest {
	if x, ok := m.GetData().(*SimDemand_SetClockRequest); ok {
		return x.SetClockRequest
	}
	return nil
}

func (m *SimDemand) GetStartClockRequest() *StartClockRequest {
	if x, ok := m.GetData().(*SimDemand_StartClockRequest); ok {
		return x.StartClockRequest
	}
	return nil
}

func (m *SimDemand) GetStopClockRequest() *StopClockRequest {
	if x, ok := m.GetData().(*SimDemand_StopClockRequest); ok {
		return x.StopClockRequest
	}
	return nil
}

func (m *SimDemand) GetForwardClockRequest() *ForwardClockRequest {
	if x, ok := m.GetData().(*SimDemand_ForwardClockRequest); ok {
		return x.ForwardClockRequest
	}
	return nil
}

func (m *SimDemand) GetGetAgentRequest() *GetAgentRequest {
	if x, ok := m.GetData().(*SimDemand_GetAgentRequest); ok {
		return x.GetAgentRequest
	}
	return nil
}

func (m *SimDemand) GetCreatePodRequest() *CreatePodRequest {
	if x, ok := m.GetData().(*SimDemand_CreatePodRequest); ok {
		return x.CreatePodRequest
	}
	return nil
}

func (m *SimDemand) GetDeletePodRequest() *DeletePodRequest {
	if x, ok := m.GetData().(*SimDemand_DeletePodRequest); ok {
		return x.DeletePodRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimDemand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimDemand_SetAgentRequest)(nil),
		(*SimDemand_RegistProviderRequest)(nil),
		(*SimDemand_UpdateProvidersRequest)(nil),
		(*SimDemand_SetClockRequest)(nil),
		(*SimDemand_StartClockRequest)(nil),
		(*SimDemand_StopClockRequest)(nil),
		(*SimDemand_ForwardClockRequest)(nil),
		(*SimDemand_GetAgentRequest)(nil),
		(*SimDemand_CreatePodRequest)(nil),
		(*SimDemand_DeletePodRequest)(nil),
	}
}

type SimSupply struct {
	MsgId    uint64 `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId uint64 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// demand type
	Type    SupplyType `protobuf:"varint,3,opt,name=type,proto3,enum=api.SupplyType" json:"type,omitempty"`
	Targets []uint64   `protobuf:"varint,4,rep,packed,name=targets,proto3" json:"targets,omitempty"`
	// meta data
	Status StatusType `protobuf:"varint,5,opt,name=status,proto3,enum=api.StatusType" json:"status,omitempty"`
	Meta   string     `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	// supply data
	//
	// Types that are valid to be assigned to Data:
	//	*SimSupply_SetAgentResponse
	//	*SimSupply_RegistProviderResponse
	//	*SimSupply_UpdateProvidersResponse
	//	*SimSupply_SetClockResponse
	//	*SimSupply_StartClockResponse
	//	*SimSupply_StopClockResponse
	//	*SimSupply_ForwardClockResponse
	//	*SimSupply_GetAgentResponse
	//	*SimSupply_CreatePodResponse
	//	*SimSupply_DeletePodResponse
	Data                 isSimSupply_Data `protobuf_oneof:"data"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimSupply) Reset()         { *m = SimSupply{} }
func (m *SimSupply) String() string { return proto.CompactTextString(m) }
func (*SimSupply) ProtoMessage()    {}
func (*SimSupply) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{1}
}

func (m *SimSupply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimSupply.Unmarshal(m, b)
}
func (m *SimSupply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimSupply.Marshal(b, m, deterministic)
}
func (m *SimSupply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimSupply.Merge(m, src)
}
func (m *SimSupply) XXX_Size() int {
	return xxx_messageInfo_SimSupply.Size(m)
}
func (m *SimSupply) XXX_DiscardUnknown() {
	xxx_messageInfo_SimSupply.DiscardUnknown(m)
}

var xxx_messageInfo_SimSupply proto.InternalMessageInfo

func (m *SimSupply) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *SimSupply) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *SimSupply) GetType() SupplyType {
	if m != nil {
		return m.Type
	}
	return SupplyType_SET_AGENT_RESPONSE
}

func (m *SimSupply) GetTargets() []uint64 {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *SimSupply) GetStatus() StatusType {
	if m != nil {
		return m.Status
	}
	return StatusType_OK
}

func (m *SimSupply) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type isSimSupply_Data interface {
	isSimSupply_Data()
}

type SimSupply_SetAgentResponse struct {
	SetAgentResponse *SetAgentResponse `protobuf:"bytes,7,opt,name=set_agent_response,json=setAgentResponse,proto3,oneof"`
}

type SimSupply_RegistProviderResponse struct {
	RegistProviderResponse *RegistProviderResponse `protobuf:"bytes,8,opt,name=regist_provider_response,json=registProviderResponse,proto3,oneof"`
}

type SimSupply_UpdateProvidersResponse struct {
	UpdateProvidersResponse *UpdateProvidersResponse `protobuf:"bytes,9,opt,name=update_providers_response,json=updateProvidersResponse,proto3,oneof"`
}

type SimSupply_SetClockResponse struct {
	SetClockResponse *SetClockResponse `protobuf:"bytes,10,opt,name=set_clock_response,json=setClockResponse,proto3,oneof"`
}

type SimSupply_StartClockResponse struct {
	StartClockResponse *StartClockResponse `protobuf:"bytes,11,opt,name=start_clock_response,json=startClockResponse,proto3,oneof"`
}

type SimSupply_StopClockResponse struct {
	StopClockResponse *StopClockResponse `protobuf:"bytes,12,opt,name=stop_clock_response,json=stopClockResponse,proto3,oneof"`
}

type SimSupply_ForwardClockResponse struct {
	ForwardClockResponse *ForwardClockResponse `protobuf:"bytes,13,opt,name=forward_clock_response,json=forwardClockResponse,proto3,oneof"`
}

type SimSupply_GetAgentResponse struct {
	GetAgentResponse *GetAgentResponse `protobuf:"bytes,14,opt,name=get_agent_response,json=getAgentResponse,proto3,oneof"`
}

type SimSupply_CreatePodResponse struct {
	CreatePodResponse *CreatePodResponse `protobuf:"bytes,15,opt,name=create_pod_response,json=createPodResponse,proto3,oneof"`
}

type SimSupply_DeletePodResponse struct {
	DeletePodResponse *DeletePodResponse `protobuf:"bytes,16,opt,name=delete_pod_response,json=deletePodResponse,proto3,oneof"`
}

func (*SimSupply_SetAgentResponse) isSimSupply_Data() {}

func (*SimSupply_RegistProviderResponse) isSimSupply_Data() {}

func (*SimSupply_UpdateProvidersResponse) isSimSupply_Data() {}

func (*SimSupply_SetClockResponse) isSimSupply_Data() {}

func (*SimSupply_StartClockResponse) isSimSupply_Data() {}

func (*SimSupply_StopClockResponse) isSimSupply_Data() {}

func (*SimSupply_ForwardClockResponse) isSimSupply_Data() {}

func (*SimSupply_GetAgentResponse) isSimSupply_Data() {}

func (*SimSupply_CreatePodResponse) isSimSupply_Data() {}

func (*SimSupply_DeletePodResponse) isSimSupply_Data() {}

func (m *SimSupply) GetData() isSimSupply_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SimSupply) GetSetAgentResponse() *SetAgentResponse {
	if x, ok := m.GetData().(*SimSupply_SetAgentResponse); ok {
		return x.SetAgentResponse
	}
	return nil
}

func (m *SimSupply) GetRegistProviderResponse() *RegistProviderResponse {
	if x, ok := m.GetData().(*SimSupply_RegistProviderResponse); ok {
		return x.RegistProviderResponse
	}
	return nil
}

func (m *SimSupply) GetUpdateProvidersResponse() *UpdateProvidersResponse {
	if x, ok := m.GetData().(*SimSupply_UpdateProvidersResponse); ok {
		return x.UpdateProvidersResponse
	}
	return nil
}

func (m *SimSupply) GetSetClockResponse() *SetClockResponse {
	if x, ok := m.GetData().(*SimSupply_SetClockResponse); ok {
		return x.SetClockResponse
	}
	return nil
}

func (m *SimSupply) GetStartClockResponse() *StartClockResponse {
	if x, ok := m.GetData().(*SimSupply_StartClockResponse); ok {
		return x.StartClockResponse
	}
	return nil
}

func (m *SimSupply) GetStopClockResponse() *StopClockResponse {
	if x, ok := m.GetData().(*SimSupply_StopClockResponse); ok {
		return x.StopClockResponse
	}
	return nil
}

func (m *SimSupply) GetForwardClockResponse() *ForwardClockResponse {
	if x, ok := m.GetData().(*SimSupply_ForwardClockResponse); ok {
		return x.ForwardClockResponse
	}
	return nil
}

func (m *SimSupply) GetGetAgentResponse() *GetAgentResponse {
	if x, ok := m.GetData().(*SimSupply_GetAgentResponse); ok {
		return x.GetAgentResponse
	}
	return nil
}

func (m *SimSupply) GetCreatePodResponse() *CreatePodResponse {
	if x, ok := m.GetData().(*SimSupply_CreatePodResponse); ok {
		return x.CreatePodResponse
	}
	return nil
}

func (m *SimSupply) GetDeletePodResponse() *DeletePodResponse {
	if x, ok := m.GetData().(*SimSupply_DeletePodResponse); ok {
		return x.DeletePodResponse
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimSupply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimSupply_SetAgentResponse)(nil),
		(*SimSupply_RegistProviderResponse)(nil),
		(*SimSupply_UpdateProvidersResponse)(nil),
		(*SimSupply_SetClockResponse)(nil),
		(*SimSupply_StartClockResponse)(nil),
		(*SimSupply_StopClockResponse)(nil),
		(*SimSupply_ForwardClockResponse)(nil),
		(*SimSupply_GetAgentResponse)(nil),
		(*SimSupply_CreatePodResponse)(nil),
		(*SimSupply_DeletePodResponse)(nil),
	}
}

type RegistProviderRequest struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegistProviderRequest) Reset()         { *m = RegistProviderRequest{} }
func (m *RegistProviderRequest) String() string { return proto.CompactTextString(m) }
func (*RegistProviderRequest) ProtoMessage()    {}
func (*RegistProviderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{2}
}

func (m *RegistProviderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistProviderRequest.Unmarshal(m, b)
}
func (m *RegistProviderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistProviderRequest.Marshal(b, m, deterministic)
}
func (m *RegistProviderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistProviderRequest.Merge(m, src)
}
func (m *RegistProviderRequest) XXX_Size() int {
	return xxx_messageInfo_RegistProviderRequest.Size(m)
}
func (m *RegistProviderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistProviderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistProviderRequest proto.InternalMessageInfo

func (m *RegistProviderRequest) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type RegistProviderResponse struct {
	Provider             *Provider `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RegistProviderResponse) Reset()         { *m = RegistProviderResponse{} }
func (m *RegistProviderResponse) String() string { return proto.CompactTextString(m) }
func (*RegistProviderResponse) ProtoMessage()    {}
func (*RegistProviderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{3}
}

func (m *RegistProviderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistProviderResponse.Unmarshal(m, b)
}
func (m *RegistProviderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistProviderResponse.Marshal(b, m, deterministic)
}
func (m *RegistProviderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistProviderResponse.Merge(m, src)
}
func (m *RegistProviderResponse) XXX_Size() int {
	return xxx_messageInfo_RegistProviderResponse.Size(m)
}
func (m *RegistProviderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistProviderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistProviderResponse proto.InternalMessageInfo

func (m *RegistProviderResponse) GetProvider() *Provider {
	if m != nil {
		return m.Provider
	}
	return nil
}

type UpdateProvidersRequest struct {
	Providers            []*Provider `protobuf:"bytes,1,rep,name=providers,proto3" json:"providers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateProvidersRequest) Reset()         { *m = UpdateProvidersRequest{} }
func (m *UpdateProvidersRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersRequest) ProtoMessage()    {}
func (*UpdateProvidersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{4}
}

func (m *UpdateProvidersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersRequest.Unmarshal(m, b)
}
func (m *UpdateProvidersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersRequest.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersRequest.Merge(m, src)
}
func (m *UpdateProvidersRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersRequest.Size(m)
}
func (m *UpdateProvidersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersRequest proto.InternalMessageInfo

func (m *UpdateProvidersRequest) GetProviders() []*Provider {
	if m != nil {
		return m.Providers
	}
	return nil
}

type UpdateProvidersResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateProvidersResponse) Reset()         { *m = UpdateProvidersResponse{} }
func (m *UpdateProvidersResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProvidersResponse) ProtoMessage()    {}
func (*UpdateProvidersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{5}
}

func (m *UpdateProvidersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateProvidersResponse.Unmarshal(m, b)
}
func (m *UpdateProvidersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateProvidersResponse.Marshal(b, m, deterministic)
}
func (m *UpdateProvidersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateProvidersResponse.Merge(m, src)
}
func (m *UpdateProvidersResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateProvidersResponse.Size(m)
}
func (m *UpdateProvidersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateProvidersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateProvidersResponse proto.InternalMessageInfo

type SetClockRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockRequest) Reset()         { *m = SetClockRequest{} }
func (m *SetClockRequest) String() string { return proto.CompactTextString(m) }
func (*SetClockRequest) ProtoMessage()    {}
func (*SetClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{6}
}

func (m *SetClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockRequest.Unmarshal(m, b)
}
func (m *SetClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockRequest.Marshal(b, m, deterministic)
}
func (m *SetClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockRequest.Merge(m, src)
}
func (m *SetClockRequest) XXX_Size() int {
	return xxx_messageInfo_SetClockRequest.Size(m)
}
func (m *SetClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockRequest proto.InternalMessageInfo

func (m *SetClockRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type SetClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetClockResponse) Reset()         { *m = SetClockResponse{} }
func (m *SetClockResponse) String() string { return proto.CompactTextString(m) }
func (*SetClockResponse) ProtoMessage()    {}
func (*SetClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{7}
}

func (m *SetClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetClockResponse.Unmarshal(m, b)
}
func (m *SetClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetClockResponse.Marshal(b, m, deterministic)
}
func (m *SetClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetClockResponse.Merge(m, src)
}
func (m *SetClockResponse) XXX_Size() int {
	return xxx_messageInfo_SetClockResponse.Size(m)
}
func (m *SetClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetClockResponse proto.InternalMessageInfo

type SetAgentRequest struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentRequest) Reset()         { *m = SetAgentRequest{} }
func (m *SetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*SetAgentRequest) ProtoMessage()    {}
func (*SetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{8}
}

func (m *SetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentRequest.Unmarshal(m, b)
}
func (m *SetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentRequest.Marshal(b, m, deterministic)
}
func (m *SetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentRequest.Merge(m, src)
}
func (m *SetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_SetAgentRequest.Size(m)
}
func (m *SetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentRequest proto.InternalMessageInfo

func (m *SetAgentRequest) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type SetAgentResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetAgentResponse) Reset()         { *m = SetAgentResponse{} }
func (m *SetAgentResponse) String() string { return proto.CompactTextString(m) }
func (*SetAgentResponse) ProtoMessage()    {}
func (*SetAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{9}
}

func (m *SetAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetAgentResponse.Unmarshal(m, b)
}
func (m *SetAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetAgentResponse.Marshal(b, m, deterministic)
}
func (m *SetAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetAgentResponse.Merge(m, src)
}
func (m *SetAgentResponse) XXX_Size() int {
	return xxx_messageInfo_SetAgentResponse.Size(m)
}
func (m *SetAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetAgentResponse proto.InternalMessageInfo

type GetAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentRequest) Reset()         { *m = GetAgentRequest{} }
func (m *GetAgentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAgentRequest) ProtoMessage()    {}
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{10}
}

func (m *GetAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentRequest.Unmarshal(m, b)
}
func (m *GetAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentRequest.Marshal(b, m, deterministic)
}
func (m *GetAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentRequest.Merge(m, src)
}
func (m *GetAgentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAgentRequest.Size(m)
}
func (m *GetAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentRequest proto.InternalMessageInfo

type GetAgentResponse struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAgentResponse) Reset()         { *m = GetAgentResponse{} }
func (m *GetAgentResponse) String() string { return proto.CompactTextString(m) }
func (*GetAgentResponse) ProtoMessage()    {}
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{11}
}

func (m *GetAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAgentResponse.Unmarshal(m, b)
}
func (m *GetAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAgentResponse.Marshal(b, m, deterministic)
}
func (m *GetAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAgentResponse.Merge(m, src)
}
func (m *GetAgentResponse) XXX_Size() int {
	return xxx_messageInfo_GetAgentResponse.Size(m)
}
func (m *GetAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAgentResponse proto.InternalMessageInfo

func (m *GetAgentResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type StartClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClockRequest) Reset()         { *m = StartClockRequest{} }
func (m *StartClockRequest) String() string { return proto.CompactTextString(m) }
func (*StartClockRequest) ProtoMessage()    {}
func (*StartClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{12}
}

func (m *StartClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClockRequest.Unmarshal(m, b)
}
func (m *StartClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClockRequest.Marshal(b, m, deterministic)
}
func (m *StartClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClockRequest.Merge(m, src)
}
func (m *StartClockRequest) XXX_Size() int {
	return xxx_messageInfo_StartClockRequest.Size(m)
}
func (m *StartClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartClockRequest proto.InternalMessageInfo

type StartClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartClockResponse) Reset()         { *m = StartClockResponse{} }
func (m *StartClockResponse) String() string { return proto.CompactTextString(m) }
func (*StartClockResponse) ProtoMessage()    {}
func (*StartClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{13}
}

func (m *StartClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartClockResponse.Unmarshal(m, b)
}
func (m *StartClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartClockResponse.Marshal(b, m, deterministic)
}
func (m *StartClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartClockResponse.Merge(m, src)
}
func (m *StartClockResponse) XXX_Size() int {
	return xxx_messageInfo_StartClockResponse.Size(m)
}
func (m *StartClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartClockResponse proto.InternalMessageInfo

type ForwardClockRequest struct {
	Clock                *Clock   `protobuf:"bytes,1,opt,name=clock,proto3" json:"clock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockRequest) Reset()         { *m = ForwardClockRequest{} }
func (m *ForwardClockRequest) String() string { return proto.CompactTextString(m) }
func (*ForwardClockRequest) ProtoMessage()    {}
func (*ForwardClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{14}
}

func (m *ForwardClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockRequest.Unmarshal(m, b)
}
func (m *ForwardClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockRequest.Marshal(b, m, deterministic)
}
func (m *ForwardClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockRequest.Merge(m, src)
}
func (m *ForwardClockRequest) XXX_Size() int {
	return xxx_messageInfo_ForwardClockRequest.Size(m)
}
func (m *ForwardClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockRequest proto.InternalMessageInfo

func (m *ForwardClockRequest) GetClock() *Clock {
	if m != nil {
		return m.Clock
	}
	return nil
}

type ForwardClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ForwardClockResponse) Reset()         { *m = ForwardClockResponse{} }
func (m *ForwardClockResponse) String() string { return proto.CompactTextString(m) }
func (*ForwardClockResponse) ProtoMessage()    {}
func (*ForwardClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{15}
}

func (m *ForwardClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ForwardClockResponse.Unmarshal(m, b)
}
func (m *ForwardClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ForwardClockResponse.Marshal(b, m, deterministic)
}
func (m *ForwardClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForwardClockResponse.Merge(m, src)
}
func (m *ForwardClockResponse) XXX_Size() int {
	return xxx_messageInfo_ForwardClockResponse.Size(m)
}
func (m *ForwardClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ForwardClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ForwardClockResponse proto.InternalMessageInfo

type StopClockRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockRequest) Reset()         { *m = StopClockRequest{} }
func (m *StopClockRequest) String() string { return proto.CompactTextString(m) }
func (*StopClockRequest) ProtoMessage()    {}
func (*StopClockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{16}
}

func (m *StopClockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockRequest.Unmarshal(m, b)
}
func (m *StopClockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockRequest.Marshal(b, m, deterministic)
}
func (m *StopClockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockRequest.Merge(m, src)
}
func (m *StopClockRequest) XXX_Size() int {
	return xxx_messageInfo_StopClockRequest.Size(m)
}
func (m *StopClockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockRequest proto.InternalMessageInfo

type StopClockResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopClockResponse) Reset()         { *m = StopClockResponse{} }
func (m *StopClockResponse) String() string { return proto.CompactTextString(m) }
func (*StopClockResponse) ProtoMessage()    {}
func (*StopClockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{17}
}

func (m *StopClockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopClockResponse.Unmarshal(m, b)
}
func (m *StopClockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopClockResponse.Marshal(b, m, deterministic)
}
func (m *StopClockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopClockResponse.Merge(m, src)
}
func (m *StopClockResponse) XXX_Size() int {
	return xxx_messageInfo_StopClockResponse.Size(m)
}
func (m *StopClockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopClockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopClockResponse proto.InternalMessageInfo

type CreatePodRequest struct {
	PodInfo              *PodInfo `protobuf:"bytes,1,opt,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodRequest) Reset()         { *m = CreatePodRequest{} }
func (m *CreatePodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodRequest) ProtoMessage()    {}
func (*CreatePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{18}
}

func (m *CreatePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodRequest.Unmarshal(m, b)
}
func (m *CreatePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodRequest.Merge(m, src)
}
func (m *CreatePodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodRequest.Size(m)
}
func (m *CreatePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodRequest proto.InternalMessageInfo

func (m *CreatePodRequest) GetPodInfo() *PodInfo {
	if m != nil {
		return m.PodInfo
	}
	return nil
}

type CreatePodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodResponse) Reset()         { *m = CreatePodResponse{} }
func (m *CreatePodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePodResponse) ProtoMessage()    {}
func (*CreatePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{19}
}

func (m *CreatePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodResponse.Unmarshal(m, b)
}
func (m *CreatePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodResponse.Merge(m, src)
}
func (m *CreatePodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePodResponse.Size(m)
}
func (m *CreatePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodResponse proto.InternalMessageInfo

type DeletePodRequest struct {
	PodInfo              *PodInfo `protobuf:"bytes,1,opt,name=pod_info,json=podInfo,proto3" json:"pod_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodRequest) Reset()         { *m = DeletePodRequest{} }
func (m *DeletePodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePodRequest) ProtoMessage()    {}
func (*DeletePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{20}
}

func (m *DeletePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodRequest.Unmarshal(m, b)
}
func (m *DeletePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodRequest.Merge(m, src)
}
func (m *DeletePodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePodRequest.Size(m)
}
func (m *DeletePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodRequest proto.InternalMessageInfo

func (m *DeletePodRequest) GetPodInfo() *PodInfo {
	if m != nil {
		return m.PodInfo
	}
	return nil
}

type DeletePodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodResponse) Reset()         { *m = DeletePodResponse{} }
func (m *DeletePodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePodResponse) ProtoMessage()    {}
func (*DeletePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{21}
}

func (m *DeletePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodResponse.Unmarshal(m, b)
}
func (m *DeletePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodResponse.Merge(m, src)
}
func (m *DeletePodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePodResponse.Size(m)
}
func (m *DeletePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodResponse proto.InternalMessageInfo

type PodInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodInfo) Reset()         { *m = PodInfo{} }
func (m *PodInfo) String() string { return proto.CompactTextString(m) }
func (*PodInfo) ProtoMessage()    {}
func (*PodInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{22}
}

func (m *PodInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodInfo.Unmarshal(m, b)
}
func (m *PodInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodInfo.Marshal(b, m, deterministic)
}
func (m *PodInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodInfo.Merge(m, src)
}
func (m *PodInfo) XXX_Size() int {
	return xxx_messageInfo_PodInfo.Size(m)
}
func (m *PodInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PodInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PodInfo proto.InternalMessageInfo

func (m *PodInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PodInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Provider struct {
	Id                   uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 ProviderType `protobuf:"varint,3,opt,name=type,proto3,enum=api.ProviderType" json:"type,omitempty"`
	Address              string       `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	ClientIds            *ClientIds   `protobuf:"bytes,6,opt,name=client_ids,json=clientIds,proto3" json:"client_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{23}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Provider) GetType() ProviderType {
	if m != nil {
		return m.Type
	}
	return ProviderType_MASTER
}

func (m *Provider) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Provider) GetClientIds() *ClientIds {
	if m != nil {
		return m.ClientIds
	}
	return nil
}

type ClientIds struct {
	ClockService         uint64   `protobuf:"varint,1,opt,name=clock_service,json=clockService,proto3" json:"clock_service,omitempty"`
	AgentService         uint64   `protobuf:"varint,2,opt,name=agent_service,json=agentService,proto3" json:"agent_service,omitempty"`
	ProviderService      uint64   `protobuf:"varint,3,opt,name=provider_service,json=providerService,proto3" json:"provider_service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientIds) Reset()         { *m = ClientIds{} }
func (m *ClientIds) String() string { return proto.CompactTextString(m) }
func (*ClientIds) ProtoMessage()    {}
func (*ClientIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{24}
}

func (m *ClientIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientIds.Unmarshal(m, b)
}
func (m *ClientIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientIds.Marshal(b, m, deterministic)
}
func (m *ClientIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientIds.Merge(m, src)
}
func (m *ClientIds) XXX_Size() int {
	return xxx_messageInfo_ClientIds.Size(m)
}
func (m *ClientIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientIds.DiscardUnknown(m)
}

var xxx_messageInfo_ClientIds proto.InternalMessageInfo

func (m *ClientIds) GetClockService() uint64 {
	if m != nil {
		return m.ClockService
	}
	return 0
}

func (m *ClientIds) GetAgentService() uint64 {
	if m != nil {
		return m.AgentService
	}
	return 0
}

func (m *ClientIds) GetProviderService() uint64 {
	if m != nil {
		return m.ProviderService
	}
	return 0
}

type Clock struct {
	GlobalTime           float64  `protobuf:"fixed64,1,opt,name=global_time,json=globalTime,proto3" json:"global_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Clock) Reset()         { *m = Clock{} }
func (m *Clock) String() string { return proto.CompactTextString(m) }
func (*Clock) ProtoMessage()    {}
func (*Clock) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{25}
}

func (m *Clock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Clock.Unmarshal(m, b)
}
func (m *Clock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Clock.Marshal(b, m, deterministic)
}
func (m *Clock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Clock.Merge(m, src)
}
func (m *Clock) XXX_Size() int {
	return xxx_messageInfo_Clock.Size(m)
}
func (m *Clock) XXX_DiscardUnknown() {
	xxx_messageInfo_Clock.DiscardUnknown(m)
}

var xxx_messageInfo_Clock proto.InternalMessageInfo

func (m *Clock) GetGlobalTime() float64 {
	if m != nil {
		return m.GlobalTime
	}
	return 0
}

type Agent struct {
	Id                   uint64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 AgentType `protobuf:"varint,3,opt,name=type,proto3,enum=api.AgentType" json:"type,omitempty"`
	Route                *Route    `protobuf:"bytes,4,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{26}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_PEDESTRIAN
}

func (m *Agent) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type Route struct {
	Position             *Coord   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Direction            float64  `protobuf:"fixed64,2,opt,name=direction,proto3" json:"direction,omitempty"`
	Speed                float64  `protobuf:"fixed64,3,opt,name=speed,proto3" json:"speed,omitempty"`
	Destination          *Coord   `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Departure            *Coord   `protobuf:"bytes,5,opt,name=departure,proto3" json:"departure,omitempty"`
	TransitPoints        []*Coord `protobuf:"bytes,6,rep,name=transit_points,json=transitPoints,proto3" json:"transit_points,omitempty"`
	NextTransit          *Coord   `protobuf:"bytes,7,opt,name=next_transit,json=nextTransit,proto3" json:"next_transit,omitempty"`
	TotalDistance        float64  `protobuf:"fixed64,8,opt,name=total_distance,json=totalDistance,proto3" json:"total_distance,omitempty"`
	RequiredTime         float64  `protobuf:"fixed64,9,opt,name=required_time,json=requiredTime,proto3" json:"required_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{27}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPosition() *Coord {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Route) GetDirection() float64 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Route) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Route) GetDestination() *Coord {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Route) GetDeparture() *Coord {
	if m != nil {
		return m.Departure
	}
	return nil
}

func (m *Route) GetTransitPoints() []*Coord {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *Route) GetNextTransit() *Coord {
	if m != nil {
		return m.NextTransit
	}
	return nil
}

func (m *Route) GetTotalDistance() float64 {
	if m != nil {
		return m.TotalDistance
	}
	return 0
}

func (m *Route) GetRequiredTime() float64 {
	if m != nil {
		return m.RequiredTime
	}
	return 0
}

type Coord struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{28}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Area struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DuplicateArea        []*Coord `protobuf:"bytes,3,rep,name=duplicate_area,json=duplicateArea,proto3" json:"duplicate_area,omitempty"`
	ControlArea          []*Coord `protobuf:"bytes,4,rep,name=control_area,json=controlArea,proto3" json:"control_area,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Area) Reset()         { *m = Area{} }
func (m *Area) String() string { return proto.CompactTextString(m) }
func (*Area) ProtoMessage()    {}
func (*Area) Descriptor() ([]byte, []int) {
	return fileDescriptor_961a558581160483, []int{29}
}

func (m *Area) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Area.Unmarshal(m, b)
}
func (m *Area) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Area.Marshal(b, m, deterministic)
}
func (m *Area) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Area.Merge(m, src)
}
func (m *Area) XXX_Size() int {
	return xxx_messageInfo_Area.Size(m)
}
func (m *Area) XXX_DiscardUnknown() {
	xxx_messageInfo_Area.DiscardUnknown(m)
}

var xxx_messageInfo_Area proto.InternalMessageInfo

func (m *Area) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Area) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Area) GetDuplicateArea() []*Coord {
	if m != nil {
		return m.DuplicateArea
	}
	return nil
}

func (m *Area) GetControlArea() []*Coord {
	if m != nil {
		return m.ControlArea
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.DemandType", DemandType_name, DemandType_value)
	proto.RegisterEnum("api.SupplyType", SupplyType_name, SupplyType_value)
	proto.RegisterEnum("api.ProviderType", ProviderType_name, ProviderType_value)
	proto.RegisterEnum("api.AgentType", AgentType_name, AgentType_value)
	proto.RegisterType((*SimDemand)(nil), "api.SimDemand")
	proto.RegisterType((*SimSupply)(nil), "api.SimSupply")
	proto.RegisterType((*RegistProviderRequest)(nil), "api.RegistProviderRequest")
	proto.RegisterType((*RegistProviderResponse)(nil), "api.RegistProviderResponse")
	proto.RegisterType((*UpdateProvidersRequest)(nil), "api.UpdateProvidersRequest")
	proto.RegisterType((*UpdateProvidersResponse)(nil), "api.UpdateProvidersResponse")
	proto.RegisterType((*SetClockRequest)(nil), "api.SetClockRequest")
	proto.RegisterType((*SetClockResponse)(nil), "api.SetClockResponse")
	proto.RegisterType((*SetAgentRequest)(nil), "api.SetAgentRequest")
	proto.RegisterType((*SetAgentResponse)(nil), "api.SetAgentResponse")
	proto.RegisterType((*GetAgentRequest)(nil), "api.GetAgentRequest")
	proto.RegisterType((*GetAgentResponse)(nil), "api.GetAgentResponse")
	proto.RegisterType((*StartClockRequest)(nil), "api.StartClockRequest")
	proto.RegisterType((*StartClockResponse)(nil), "api.StartClockResponse")
	proto.RegisterType((*ForwardClockRequest)(nil), "api.ForwardClockRequest")
	proto.RegisterType((*ForwardClockResponse)(nil), "api.ForwardClockResponse")
	proto.RegisterType((*StopClockRequest)(nil), "api.StopClockRequest")
	proto.RegisterType((*StopClockResponse)(nil), "api.StopClockResponse")
	proto.RegisterType((*CreatePodRequest)(nil), "api.CreatePodRequest")
	proto.RegisterType((*CreatePodResponse)(nil), "api.CreatePodResponse")
	proto.RegisterType((*DeletePodRequest)(nil), "api.DeletePodRequest")
	proto.RegisterType((*DeletePodResponse)(nil), "api.DeletePodResponse")
	proto.RegisterType((*PodInfo)(nil), "api.PodInfo")
	proto.RegisterType((*Provider)(nil), "api.Provider")
	proto.RegisterType((*ClientIds)(nil), "api.ClientIds")
	proto.RegisterType((*Clock)(nil), "api.Clock")
	proto.RegisterType((*Agent)(nil), "api.Agent")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*Coord)(nil), "api.Coord")
	proto.RegisterType((*Area)(nil), "api.Area")
}

func init() { proto.RegisterFile("simulation.proto", fileDescriptor_961a558581160483) }

var fileDescriptor_961a558581160483 = []byte{
	// 1562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x6e, 0xdb, 0x48,
	0x12, 0x36, 0xf5, 0xaf, 0xb2, 0x2c, 0x53, 0x6d, 0x4b, 0x96, 0x93, 0x2c, 0x22, 0x30, 0x9b, 0x8d,
	0xe3, 0x5d, 0x07, 0x48, 0x82, 0xdd, 0x3d, 0xec, 0x49, 0xb6, 0x18, 0x47, 0x70, 0xd6, 0x52, 0x9a,
	0x74, 0x8c, 0xcd, 0x45, 0x60, 0xc4, 0xb6, 0x40, 0xac, 0x24, 0x32, 0x6c, 0x2a, 0xbb, 0xb9, 0xcd,
	0x61, 0x0e, 0x73, 0x98, 0xd3, 0x3c, 0xc0, 0xbc, 0xd0, 0x3c, 0xc9, 0xbc, 0xc5, 0xa0, 0x7f, 0x48,
	0x91, 0x4d, 0x0e, 0xe0, 0x00, 0x73, 0xa3, 0xbe, 0xaf, 0xf8, 0xb1, 0xab, 0xba, 0xbe, 0x2e, 0x52,
	0xa0, 0x53, 0x6f, 0xb5, 0x59, 0x3a, 0x91, 0xe7, 0xaf, 0x5f, 0x04, 0xa1, 0x1f, 0xf9, 0xa8, 0xec,
	0x04, 0x9e, 0xf1, 0x7d, 0x1d, 0x9a, 0x96, 0xb7, 0x1a, 0x91, 0x95, 0xb3, 0x76, 0x51, 0x17, 0x6a,
	0x2b, 0xba, 0x98, 0x79, 0x6e, 0x5f, 0x1b, 0x68, 0x27, 0x15, 0x5c, 0x5d, 0xd1, 0xc5, 0xd8, 0x45,
	0x0f, 0xa1, 0x49, 0xc9, 0xda, 0x25, 0x21, 0x63, 0x4a, 0x9c, 0x69, 0x08, 0x60, 0xec, 0xa2, 0x27,
	0x50, 0x89, 0xbe, 0x06, 0xa4, 0x5f, 0x1e, 0x68, 0x27, 0xed, 0x57, 0xfb, 0x2f, 0x9c, 0xc0, 0x7b,
	0x21, 0xe4, 0xec, 0xaf, 0x01, 0xc1, 0x9c, 0x44, 0x7d, 0xa8, 0x47, 0x4e, 0xb8, 0x20, 0x11, 0xed,
	0x57, 0x06, 0xe5, 0x93, 0x0a, 0x8e, 0x7f, 0x22, 0x04, 0x95, 0x15, 0x89, 0x9c, 0x7e, 0x75, 0xa0,
	0x9d, 0x34, 0x31, 0xbf, 0x46, 0xe7, 0xd0, 0xa1, 0x24, 0x9a, 0x39, 0x0b, 0xb2, 0x8e, 0x66, 0x21,
	0xf9, 0xbc, 0x21, 0x34, 0xea, 0xd7, 0x06, 0xda, 0xc9, 0xee, 0xab, 0x43, 0xae, 0x6f, 0x91, 0x68,
	0xc8, 0x48, 0x2c, 0xb8, 0xb7, 0x3b, 0x78, 0x9f, 0x66, 0x21, 0x64, 0xc3, 0x51, 0x48, 0x16, 0x1e,
	0x8d, 0x66, 0x41, 0xe8, 0x7f, 0xf1, 0xd8, 0xe2, 0x63, 0xa5, 0x3a, 0x57, 0x7a, 0xc0, 0x95, 0x30,
	0x8f, 0x99, 0xca, 0x90, 0xad, 0x5e, 0x37, 0x2c, 0x22, 0xd0, 0x2d, 0xf4, 0x37, 0x81, 0xeb, 0x44,
	0x24, 0x51, 0xa5, 0x89, 0x6c, 0x83, 0xcb, 0x3e, 0xe4, 0xb2, 0x37, 0x3c, 0x28, 0xbe, 0x9b, 0x6e,
	0x75, 0x7b, 0x9b, 0x42, 0x26, 0x4e, 0x79, 0xbe, 0xf4, 0xe7, 0xff, 0x4d, 0x14, 0x9b, 0xd9, 0x94,
	0x2f, 0x18, 0x99, 0x4d, 0x39, 0x0d, 0xa1, 0xb7, 0x70, 0x40, 0x23, 0x27, 0x54, 0x55, 0x80, 0xab,
	0xf4, 0x84, 0x0a, 0xe3, 0x15, 0x9d, 0x0e, 0x55, 0x41, 0x64, 0x02, 0xa2, 0x91, 0x1f, 0x28, 0x42,
	0xbb, 0x5c, 0xa8, 0x2b, 0x85, 0xfc, 0x40, 0xd1, 0xd1, 0xa9, 0x82, 0xa1, 0x6b, 0xe8, 0xde, 0xf9,
	0xe1, 0xff, 0x9c, 0xd0, 0x55, 0x94, 0x5a, 0x5c, 0xa9, 0xcf, 0x95, 0xde, 0x88, 0x08, 0x45, 0xec,
	0xe0, 0x2e, 0x0f, 0xb3, 0x22, 0x2d, 0x72, 0x7d, 0xb1, 0x97, 0x2a, 0xd2, 0x65, 0xbe, 0x2f, 0x16,
	0x4a, 0x5f, 0x98, 0x80, 0xe6, 0x21, 0xe1, 0x3b, 0xe8, 0xbb, 0x89, 0x48, 0x3b, 0x95, 0xda, 0x05,
	0xa7, 0xa7, 0xbe, 0x9b, 0x4a, 0x6d, 0xae, 0x60, 0x4c, 0xc6, 0x25, 0x4b, 0xa2, 0xc8, 0xec, 0xa7,
	0x64, 0x46, 0x9c, 0xce, 0xca, 0xb8, 0x0a, 0x76, 0x5e, 0x83, 0x8a, 0xeb, 0x44, 0x8e, 0xf1, 0x8b,
	0xb0, 0xa1, 0xb5, 0x09, 0x82, 0xe5, 0xd7, 0x3f, 0xcc, 0x86, 0x42, 0xee, 0x5e, 0x36, 0x7c, 0x06,
	0x35, 0x1a, 0x39, 0xd1, 0x86, 0x72, 0x23, 0x26, 0x02, 0x1c, 0xe2, 0x02, 0x92, 0x4e, 0xfc, 0x5a,
	0x4b, 0xf9, 0x95, 0xb5, 0x4b, 0x6a, 0x5f, 0x68, 0xe0, 0xaf, 0x29, 0x91, 0x36, 0xeb, 0x2a, 0x86,
	0x15, 0x24, 0x6f, 0x17, 0x05, 0x63, 0xe6, 0xca, 0x5b, 0x56, 0x8a, 0xa5, 0xcd, 0xa5, 0x7a, 0x36,
	0x91, 0xec, 0x85, 0x85, 0x0c, 0xfa, 0x08, 0xc7, 0x05, 0xae, 0x95, 0xca, 0xc2, 0x64, 0x8f, 0x8a,
	0x6d, 0x9b, 0x48, 0x1f, 0x6d, 0x8a, 0xa9, 0x38, 0xf7, 0xb8, 0xbf, 0xa5, 0x28, 0x64, 0x73, 0x97,
	0x5d, 0x9c, 0xc9, 0x3d, 0x83, 0xa1, 0x2b, 0x38, 0xcc, 0x7a, 0x57, 0x0a, 0x09, 0xcf, 0x1d, 0xe5,
	0xcc, 0x9b, 0x48, 0x21, 0x9a, 0x43, 0xc5, 0x41, 0x90, 0xb2, 0xaf, 0xd4, 0x6a, 0x65, 0x0e, 0x82,
	0xc4, 0xab, 0x89, 0x54, 0x87, 0xaa, 0x20, 0x7a, 0x0f, 0x3d, 0xd5, 0xc1, 0x52, 0x4c, 0xd8, 0xee,
	0xb8, 0xc0, 0xc2, 0x89, 0xde, 0xe1, 0x5d, 0x01, 0xce, 0x0a, 0xb6, 0xc8, 0x37, 0x4b, 0xda, 0x80,
	0x97, 0x05, 0xcd, 0xb2, 0x50, 0x9b, 0xe5, 0x2d, 0x1c, 0x64, 0x7c, 0x2c, 0x75, 0xf6, 0x53, 0x39,
	0xa6, 0x8c, 0xbc, 0xcd, 0x71, 0xae, 0x82, 0x4c, 0x29, 0x63, 0x65, 0xa9, 0xa4, 0xa7, 0x94, 0x52,
	0x5e, 0xde, 0x2a, 0xb9, 0x2a, 0x98, 0xb8, 0xf9, 0x1c, 0xba, 0x85, 0x73, 0x05, 0x3d, 0x87, 0x46,
	0xdc, 0x81, 0xdc, 0xda, 0xbb, 0xaf, 0xf6, 0xb8, 0x7e, 0x12, 0x97, 0xd0, 0xc6, 0x05, 0xf4, 0x8a,
	0xfb, 0xfc, 0x5b, 0x44, 0x4c, 0xe8, 0x15, 0x4f, 0x22, 0xf4, 0x57, 0x68, 0x26, 0x5e, 0xe8, 0x6b,
	0x83, 0x72, 0x5e, 0x65, 0xcb, 0x1b, 0xc7, 0x70, 0xf4, 0x3b, 0xce, 0x30, 0x5e, 0xc3, 0xbe, 0x32,
	0x99, 0xd0, 0x00, 0xaa, 0xbc, 0x57, 0xe4, 0xe2, 0x40, 0xec, 0x05, 0x8f, 0x10, 0x84, 0x81, 0x40,
	0x57, 0x4d, 0x61, 0xfc, 0x9d, 0x0b, 0x65, 0x8e, 0x6a, 0x03, 0x6a, 0xbc, 0x4b, 0xe2, 0x05, 0x0a,
	0x25, 0x11, 0x22, 0x19, 0x29, 0x95, 0x69, 0x0d, 0xa3, 0x03, 0xfb, 0xca, 0x20, 0x30, 0xfe, 0x01,
	0xba, 0xda, 0x55, 0xf7, 0x92, 0x3f, 0x80, 0x4e, 0x6e, 0x64, 0x1a, 0x87, 0x80, 0xf2, 0x56, 0x34,
	0xfe, 0x09, 0x07, 0x05, 0xa3, 0xec, 0x1e, 0xd5, 0xe8, 0xc1, 0x61, 0x91, 0x81, 0x78, 0x6a, 0xca,
	0x44, 0x15, 0xeb, 0x51, 0x4c, 0x6a, 0xfc, 0x0b, 0x74, 0x75, 0x66, 0xa1, 0x67, 0xd0, 0x60, 0xdd,
	0xec, 0xad, 0xef, 0x7c, 0xf9, 0xe4, 0x96, 0xd8, 0x5e, 0xdf, 0x1d, 0xaf, 0xef, 0x7c, 0x5c, 0x0f,
	0xc4, 0x05, 0x53, 0xcc, 0xf9, 0x84, 0x29, 0xaa, 0xe3, 0xeb, 0x9b, 0x14, 0x73, 0x7e, 0x31, 0xce,
	0xa0, 0x2e, 0x03, 0x51, 0x1b, 0x4a, 0xc9, 0x64, 0x2b, 0x79, 0x2e, 0x9b, 0x28, 0x6b, 0x67, 0x45,
	0xf8, 0x44, 0x6b, 0x62, 0x7e, 0x6d, 0xfc, 0xac, 0x41, 0x23, 0x6e, 0xb6, 0xfb, 0xdc, 0x80, 0x9e,
	0x66, 0xc6, 0x5f, 0x27, 0xd3, 0xca, 0xd9, 0x01, 0xe8, 0xb8, 0x6e, 0x48, 0x28, 0x95, 0x2f, 0x9c,
	0xf1, 0x4f, 0x74, 0x06, 0x30, 0x5f, 0x7a, 0xec, 0x4c, 0xf2, 0x5c, 0x2a, 0x5f, 0x36, 0xdb, 0x72,
	0xb3, 0x18, 0x3c, 0x76, 0x29, 0x6e, 0xce, 0xe3, 0x4b, 0xe3, 0x3b, 0x0d, 0x9a, 0x09, 0x81, 0x9e,
	0xc0, 0x9e, 0x38, 0x1e, 0x29, 0x09, 0xbf, 0x78, 0x73, 0x22, 0x17, 0xdb, 0xe2, 0xa0, 0x25, 0x30,
	0x16, 0x24, 0x0e, 0xbd, 0x38, 0x48, 0x8c, 0xf0, 0x16, 0x07, 0xe3, 0xa0, 0xe7, 0xa0, 0x27, 0xc3,
	0x2f, 0x8e, 0x2b, 0xf3, 0xb8, 0xfd, 0x18, 0x97, 0xa1, 0xc6, 0x09, 0x54, 0x79, 0x1f, 0xa0, 0xc7,
	0xb0, 0xbb, 0x58, 0xfa, 0x9f, 0x9c, 0xe5, 0x2c, 0xf2, 0x56, 0xe2, 0xd9, 0x1a, 0x06, 0x01, 0xd9,
	0xde, 0x8a, 0x18, 0x9f, 0xa1, 0xca, 0xdb, 0xfa, 0x5e, 0x95, 0x34, 0x32, 0x95, 0x6c, 0x6f, 0x4d,
	0x91, 0x2a, 0xe3, 0x00, 0xaa, 0xa1, 0xbf, 0x89, 0x48, 0xbf, 0x92, 0x6a, 0x6a, 0xcc, 0x10, 0x2c,
	0x08, 0xe3, 0xd7, 0x12, 0x54, 0x39, 0x80, 0xfe, 0xc2, 0xfa, 0x86, 0x7a, 0xec, 0xc3, 0x23, 0xeb,
	0x01, 0xdf, 0x0f, 0x5d, 0x9c, 0x70, 0xe8, 0x11, 0x34, 0x5d, 0x2f, 0x24, 0x73, 0x1e, 0x58, 0xe2,
	0x39, 0x6c, 0x01, 0x74, 0x08, 0x55, 0x1a, 0x10, 0xe2, 0xf2, 0x65, 0x69, 0x58, 0xfc, 0x40, 0x7f,
	0x83, 0x5d, 0x97, 0xd0, 0xc8, 0x5b, 0xf3, 0xef, 0x9a, 0xcc, 0x6a, 0x84, 0x7c, 0x9a, 0x46, 0x27,
	0xd0, 0x74, 0x49, 0xe0, 0x84, 0xd1, 0x26, 0x24, 0x7c, 0xfb, 0xb3, 0xb1, 0x5b, 0x12, 0xbd, 0x84,
	0x76, 0x14, 0x3a, 0x6b, 0xea, 0x45, 0xb3, 0xc0, 0xf7, 0xd8, 0x11, 0x51, 0x4b, 0x1d, 0x11, 0x22,
	0x7c, 0x4f, 0x46, 0x4c, 0x79, 0x00, 0x3a, 0x83, 0xd6, 0x9a, 0xfc, 0x3f, 0x9a, 0x49, 0x54, 0xbe,
	0xfd, 0x64, 0xd6, 0xc2, 0x78, 0x5b, 0xd0, 0xe8, 0x29, 0xb4, 0x23, 0x3f, 0x72, 0x96, 0x33, 0xd7,
	0xa3, 0x91, 0xb3, 0x9e, 0x8b, 0x37, 0x1c, 0x0d, 0xef, 0x71, 0x74, 0x24, 0x41, 0xd6, 0x33, 0xec,
	0xdd, 0xd2, 0x0b, 0x89, 0x2b, 0x36, 0xb7, 0xc9, 0xa3, 0x5a, 0x31, 0xc8, 0xb7, 0x77, 0x08, 0x55,
	0xfe, 0x04, 0xf4, 0x00, 0x1a, 0xec, 0x0b, 0x2f, 0xda, 0xb8, 0x71, 0x17, 0x24, 0xbf, 0x59, 0x79,
	0x97, 0xfe, 0x7a, 0x21, 0x48, 0x59, 0xde, 0x04, 0x30, 0x7e, 0xd4, 0xa0, 0x32, 0x0c, 0x89, 0x73,
	0xaf, 0x0e, 0x79, 0x09, 0x6d, 0x77, 0x13, 0x2c, 0xbd, 0x39, 0x9b, 0xbe, 0x4e, 0x48, 0x9c, 0x7e,
	0x39, 0x5f, 0x9d, 0x24, 0x82, 0xcb, 0x9e, 0x41, 0x6b, 0xee, 0xaf, 0xa3, 0xd0, 0x5f, 0x8a, 0x1b,
	0x2a, 0xb9, 0x1b, 0x76, 0x25, 0xcf, 0xc2, 0x4f, 0x1f, 0x03, 0x6c, 0x5f, 0x3d, 0x51, 0x0d, 0x4a,
	0x93, 0x2b, 0x7d, 0x07, 0x35, 0xa1, 0x6a, 0x62, 0x3c, 0xc1, 0xba, 0x76, 0xfa, 0x43, 0x09, 0x60,
	0xfb, 0x91, 0x89, 0xba, 0xd0, 0xb1, 0x4c, 0x7b, 0x36, 0xbc, 0x34, 0xaf, 0xed, 0x19, 0x36, 0xdf,
	0xdf, 0x98, 0x96, 0xad, 0xef, 0x30, 0xf8, 0x32, 0x07, 0x6b, 0xe8, 0x21, 0x1c, 0x61, 0xf3, 0x72,
	0x6c, 0xd9, 0xb3, 0x29, 0x9e, 0x7c, 0x18, 0x8f, 0x4c, 0x9c, 0x90, 0x25, 0xf4, 0x08, 0xfa, 0x37,
	0xd3, 0xd1, 0xd0, 0x36, 0x13, 0xd2, 0x4a, 0xd8, 0x72, 0xfc, 0xa0, 0x8b, 0x77, 0x93, 0x8b, 0xab,
	0x04, 0xae, 0xa0, 0x23, 0x38, 0xb0, 0xec, 0x21, 0x56, 0x89, 0x2a, 0xea, 0x01, 0xb2, 0xec, 0xc9,
	0x54, 0xc1, 0x6b, 0xe8, 0x18, 0xba, 0x6f, 0x26, 0xf8, 0x76, 0x88, 0x47, 0x0a, 0x55, 0x67, 0xb7,
	0x5c, 0x60, 0x93, 0x2f, 0x60, 0x32, 0x4a, 0xf0, 0x06, 0xc3, 0x47, 0xe6, 0x3b, 0x53, 0xc1, 0x9b,
	0xa7, 0x3f, 0x95, 0x00, 0xb6, 0x2f, 0xfa, 0xfc, 0x89, 0xa9, 0x9c, 0xad, 0xe9, 0xe4, 0xda, 0x32,
	0xf5, 0x1d, 0x86, 0x5f, 0xe6, 0x71, 0x8d, 0xe5, 0x9b, 0x2f, 0x86, 0x64, 0x4b, 0xe8, 0x4f, 0x70,
	0x5c, 0x50, 0x0d, 0x49, 0x97, 0xe3, 0x87, 0xc5, 0x29, 0x48, 0xbc, 0x82, 0xfa, 0x70, 0x98, 0xad,
	0x87, 0x64, 0xaa, 0xa2, 0x52, 0xa9, 0x82, 0x48, 0xa2, 0x86, 0x1e, 0x40, 0x4f, 0xad, 0x88, 0xe4,
	0xea, 0xec, 0xa6, 0x4c, 0x49, 0x24, 0xd1, 0x60, 0x44, 0xa6, 0x26, 0x92, 0x68, 0x9e, 0xbe, 0x87,
	0x56, 0xfa, 0xf4, 0x47, 0x00, 0xb5, 0x7f, 0x0f, 0x2d, 0xdb, 0xc4, 0xfa, 0x0e, 0xbb, 0xbe, 0x9d,
	0xe0, 0x2b, 0x13, 0xeb, 0x1a, 0x6b, 0x29, 0x5e, 0x11, 0xbd, 0x84, 0x3a, 0xb0, 0xf7, 0x61, 0x6c,
	0xdd, 0x0c, 0xdf, 0x8d, 0x3f, 0x0e, 0xed, 0xf1, 0xe4, 0x5a, 0x2f, 0xa3, 0x5d, 0xa8, 0x5f, 0x0e,
	0x6d, 0xf3, 0x76, 0xf8, 0x1f, 0xbd, 0x72, 0xfa, 0x67, 0x68, 0x26, 0xc7, 0x20, 0x6a, 0x03, 0x4c,
	0xcd, 0x91, 0x69, 0xd9, 0x78, 0x3c, 0xbc, 0xd6, 0x77, 0x50, 0x1d, 0xca, 0x17, 0x43, 0xac, 0x6b,
	0xe7, 0xd5, 0x8f, 0x65, 0x27, 0xf0, 0x3e, 0xd5, 0xf8, 0x5f, 0x2c, 0xaf, 0x7f, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x5a, 0x9f, 0x38, 0xfc, 0x76, 0x11, 0x00, 0x00,
}
